### ISSUE TITLE
Being able to pass options to the `node-fetch` (eg. timeout)

### ISSUE THREAD

**Issue by lizell** [agraboso/redux-api-middleware#102]
This would allow us to specify set a read timeout or controlling redirect behavior and more.

See #101 for implementation.

**Comment by dentrado** [comment]
This issue can be closed now I think? Fixed in https://github.com/agraboso/redux-api-middleware/pull/150

**Comment by lizell** [comment]
But only merged into `next` as of now. Any idea of when next will be released?

**Comment by nason** [comment]
Released in `2.0.0` @lizell! I'll close this out now 🎋

**Comment by lizell** [comment]
Superb!
