### ISSUE TITLE
Can't find variable: self?

### ISSUE THREAD

**Issue by karolbarkowski** [agraboso/redux-api-middleware#106]
Hi,
I recently added redux-api-middleware to my project and everything is working fine as long as I'm in debugger mode. But once I exit the debug mode it throws "Can't find cariable: self" error when app is starting.
I got all my packages updated. RN is in latest version (0.34.1 when I'm writing this).
Anyone noticed anything similar before? It's quite tricky to even know what can be wrong as I can't debug anything (it's working when debugger is on).
I'm also sure that it's none of my existing packages.

Thanks in advance for any help.

**Comment by karolbarkowski** [comment]
Aaah, crap. Looks like it's because redux-api-middleware simply doesn't work with react native as I initially thought. Sorry, my bad. Closing.

**Comment by etaiklein** [comment]
@karolbarkowski I'm running into the same problem trying to get R-A-M working with RN. Did you end up getting this working? What did you do differently?
