### ISSUE TITLE
Browser ignores Set-Cookie in CORS request

### ISSUE THREAD

**Issue by daniula** [agraboso/redux-api-middleware#108]
I'm making `DELETE` request from `example.com` to `api.example.com` with `credentials: include`. Server response has `Set-Cookie` header with new value but Chrome v54 ignores it.

When I'm making the same request with native `fetch` cookies are updated properly:

```
fetch('//api.example.com/auth/login', { method: 'DELETE', credentials: 'include' })
```

**Comment by abimelex** [comment]
Did you found a solution fro this? Seems I have the same problem here...

**Comment by daniula** [comment]
@abimelex In that case for `DELETE` requests I wrote actions with `redux-thunk` using `fetch` API directly. In the next project I decided to use `axios` and `redux-axios-middleware`.

**Comment by abimelex** [comment]
```
return {
        [CALL_API]: {
            endpoint,
            method,
            credentials: 'include', // this line is important!
```

**Comment by nason** [comment]
Thanks @abimelex -- closing this out
