### ISSUE TITLE
normalizr is being required, but not used or listed in dependencies

### ISSUE THREAD

**Issue by latentflip** [agraboso/redux-api-middleware#11]
This line: https://github.com/agraboso/redux-api-middleware/blob/master/src/validateRSAA.js#L2 is requiring normalizr, but it's not listed as a dependency anywhere, so it blows up if you haven't installed normalizr in your app.

I would PR, but I seem to be unable to run npm install in this repo at the moment. Computers!

**Comment by agraboso** [comment]
I forgot to delete that line when moving to `[CALL_API].transform`. `normalizr` is required as a dev dependency, so test were passing.
