### ISSUE TITLE
redux-actions's update cause redux-api-middleware error

### ISSUE THREAD

**Issue by geminiyellow** [agraboso/redux-api-middleware#110]
when i update [redux-action](https://github.com/acdlite/redux-actions) to v1.0.0,
`isFSA` cause the `Uncaught Error: The FSA spec mandates an action object with a type. Try using the createAction(s) method.` error.

**Comment by nason** [comment]
I use both `redux-api-middleware` and `redux-actions`, but RSAAs are not FSAs. I'm not sure what the bug is here, so I'm going to close.

Please re-open if this is an ongoing issue, with steps to reproduce if possible.
