### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by stephenmathieson** [agraboso/redux-api-middleware#111]
Any plans to add support? I think all we need is #58 to land.

**Comment by yasaichi** [comment]
@stephenmathieson 
Since I'd like to do that, I created [@yasaichi/redux-api-middleware](https://github.com/yasaichi/redux-api-middleware).
It allows you to use any `fetch` implementations as follows:

```js
import { createStore, applyMiddleware, combineReducers } from 'redux';
import { apiMiddlewareCreator } from '@yasaichi/redux-api-middleware';
import reducers from './reducers';

const apiMiddleware = apiMiddlewareCreator(fetch);
const createStoreWithMiddleware = applyMiddleware(apiMiddleware)(createStore);
const reducer = combineReducers(reducers);

export default function configureStore(initialState) {
  return createStoreWithMiddleware(reducer, initialState);
}
```

How would you like to try it? (currently it works only on v0.41.0-rc.0 :bow:)

**Comment by stephenmathieson** [comment]
@yasaichi I ended up finishing my RN project and don't have an immediate need for this. I will check it out in the next few days tho!!

**Comment by jordanmkoncz** [comment]
Thanks @yasaichi, I'm now using your fork and everything seems to be working correctly.

**Comment by agraboso** [comment]
The `next` branch (which will lead to version 2) removes `isomorphic-fetch` in favor of the global `fetch`.
