### ISSUE TITLE
Should I use a reducer for each API all?

### ISSUE THREAD

**Issue by hecontreraso** [agraboso/redux-api-middleware#112]
Reading the docs, I feel like this is the correct way to use the library. So we can have at minimum this data in the store per API call:

        isFetching
        isError
        data

Am I getting it wrong or is ok to design my app like this?

Thanks!

**Comment by nason** [comment]
Hi @hecontreraso, sure! I think this is a valid approach. I've used a similar structure in a few API-handling reducers.
