### ISSUE TITLE
Document promise polyfill dependency for v1

### ISSUE THREAD

**Issue by amangeot** [agraboso/redux-api-middleware#113]
Hello,
I had an issue with requests using `redux-api-middleware` in Android KitKat's `WebView`. I just realized that `isomorphic-fetch` requires a polyfill for `Promise`s (e.g. `es6-promise`) to run in older browsers.

It could be nice to add a line about it in `redux-api-middleware` documentation, in order to save some debugging time!

KitKat's WebView runs a code based on Chrome for Android v30, and is installed on 24% of Android devices as of today.

**Comment by nason** [comment]
Thanks for the report. This is great feedback and we can certainly add some docs around this to v1 (`Promise` polyfill required) and to v2 (`fetch` polyfill required)

**Comment by mlippens** [comment]
@nason In v2, isomorphic-fetch will no longer be included as dependency?

**Comment by nason** [comment]
That's correct @mlippens-- redux-api-middleware v2 will use the global fetch method instead of using its own internal fetch
