### ISSUE TITLE
NOT AN ISSUE: when 2.0.0 is going to be released?

### ISSUE THREAD

**Issue by felixcrive** [agraboso/redux-api-middleware#115]
I wonder if the plans for releasing 2.0.0 are soon. Reviewing the branch (next) I see the changes for removing Symbol and using RSAA instead.

**Comment by Bigdragon13th** [comment]
I'm having the same question.

**Comment by moderndegree** [comment]
Is this project being maintained? The last commit I see was made Apr 25, 2016.

**Comment by KarlJakober** [comment]
doesnt seem like it :hankey:

**Comment by moderndegree** [comment]
@agraboso You might want to consider passing this project on to someone else.

**Comment by mlippens** [comment]
I second that, @agraboso we should find another maintainer that can address the issues and the work already done for 2.0 release. I assume most people are just forking now like I am to address the issues I am having.

**Comment by agraboso** [comment]
#124
