### ISSUE TITLE
Returning status codes?

### ISSUE THREAD

**Issue by keith-gould-zocdoc** [agraboso/redux-api-middleware#117]
SUCCESS is triggered in the 200 range and FAILURE is triggered for anything outside the 200 range.  However, we only get 'type' and 'payload' back, not the exact status code.  One of the big reasons we can't really use redux-api-middleware in our work is that we also need that status code.

Is there any way to get status codes that I'm simply missing?  If not would you guys be open to adding them to the SUCCESS / FAILURE calls if I was to put up a PR?

**Comment by developer239** [comment]
Have you tried meta property?

```
    meta: (action, state, res) => {
          if (res) {
            return {
              status: res.status
              statusText: res.statusText
            };
          } else {
            return {
              status: 'Network request failed'
            }
          }
        }
```

**Comment by keith-gould-zocdoc** [comment]
@developer239 that looks like it should work.  Let me try that.  I'll close the issue for now as well.
