### ISSUE TITLE
Add support for React Native, remove and replace `isomorphic-fetch`

### ISSUE THREAD

**Issue by Connorelsea** [agraboso/redux-api-middleware#119]
Hello, I really like this library and use it quite frequently, but currently, it does not work with React Native.

This malfunction is due to `redux-api-middleware`'s dependency on `isomorphic-fetch`, which has opted to not support React Native users. Despite [Github implementing a similar fix](https://github.com/github/fetch/pull/253) on their equivalent library, `isomorphic-fetch` has chosen [not to](https://github.com/matthew-andrews/isomorphic-fetch/pull/63).

Due to this, some other projects have switched from `isomorphic-fetch` to `fetch-everywhere` in order to retain the same functionality while also supporting React Native. `fetch-everywhere` is an alternative library built using the same dependencies as `isomorphic-fetch`, but it includes support for React Native.

Would you consider switching fetch libraries in order to support React Native?

I am not faulting the maintainer of `isomorphic-fetch`, as I am fully aware people have lives outside of open source, but it is seemingly unmaintained. As of right now, `fetch-everywhere` seems like a better solution. Switching libraries will allow React Native users to use `redux-api-middleware` while also allowing users on other platforms to remain unaffected.

## Examples of RN Fetch Issues Occuring

Here is one of the initial threads about this issue: https://github.com/matthew-andrews/isomorphic-fetch/pull/63

Here is a continued thread about the issues that has yet to be merged. https://github.com/matthew-andrews/isomorphic-fetch/issues/125

Here is a thread showing the maintainer's unwillingness to merge the fix, indicating a need for dependent libraries to switch if they wish to support React Native users: https://github.com/matthew-andrews/isomorphic-fetch/pull/80

## Github's Solution

https://github.com/github/fetch/pull/253

## Libraries Switching from isomorphic-fetch to fetch-everywhere

Here is an example of another library removing `isomorphic-fetch`: https://github.com/dixieio/redux-json-api/pull/91

**Comment by mlippens** [comment]
Why not just use global fetch and remove the import statement all together? Then the consumer of the library is responsible for providing the correct implementation instead. Is this also a viable solution for React Native?

**Comment by agraboso** [comment]
The `next` branch (which will lead to version 2) removes `isomorphic-fetch` in favor of the global `fetch`.

**Comment by mayyamak** [comment]
@agraboso We are expecting version 2.
When would you release it?

**Comment by nason** [comment]
@mayyamak I am working on it, but don't have a lot of time to give to this project. There is a beta published to npm, based on the 'next' branch.

There are a few things left to do. You're more than welcome to contribute.
