### ISSUE TITLE
Header middleware

### ISSUE THREAD

**Issue by RanzQ** [agraboso/redux-api-middleware#12]
I created a middleware which adds an authentication token but for some reason the header key gets converted to lowercase. Not actually a problem but I just wonder why. Does this issue originate from isomorphic-fetch or what?

My middleware:

```
import { CALL_API } from 'redux-api-middleware'

const authMiddleware = ({getState, dispatch}) => next => action => {

  console.log('authMiddleware', action)

  if (!action[CALL_API]) {
    return next(action)
  }
  return next({
    ...action,
    [CALL_API]: {
      headers: {
        Authorization: 'Bearer ' + getState().token,
        ...action[CALL_API].headers
      },
      ...action[CALL_API]
    }
  })
}

export default authMiddleware
```

I tried with `Authorization`, `'Authorization'` and `['Authorization']`

**Comment by agraboso** [comment]
`redux-api-middleware` doesn't modify the headers in any way &mdash; you don't have to believe me: just look at the code &mdash;, so it is either `isomorphic-fetch` or your code &mdash; either client or server.

I'm closing this for now, since I sincerely believe it is not `redux-api-middleware`'s fault. But if you find out it is, please let me know by reopening this issue.

**Comment by RanzQ** [comment]
Thank you, I'll dig in deeper. With github's fetch this didn't happen. Anyway, that's a working example of a header middleware so I decided to post it here if someone wonders how to do it. Just have to chain that before `redux-api-middleware`.

**Comment by developer239** [comment]
But did you find solution?

**Comment by RanzQ** [comment]
@developer239 solution was that it's not a problem. Server should read headers case-insensitive. If you use fetch, you will get lowercase headers.

**Comment by developer239** [comment]
Could you please send me any link with more explenation why? Or other source of that standard so that I could send it to backend?

**Comment by developer239** [comment]
OK I think this will help other who get stuck on the same problem:

http://stackoverflow.com/a/5259004/4766136
