### ISSUE TITLE
301redirects with POST results in GET

### ISSUE THREAD

**Issue by KarlJakober** [agraboso/redux-api-middleware#121]
Currently after the 301 the resulting request is GET, resulting in an incorrect response from the server

**Comment by TheSharpieOne** [comment]
This is the browser's doing, not this library.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.2
> If the 301 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.
>> Note: When automatically redirecting a POST request after receiving a 301 status code, some existing HTTP/1.0 user agents will erroneously change it into a GET request.

In HTTP 1.1, there actually is a status code (307) which indicates that the request should be repeated using the same method and post data.

**Comment by nason** [comment]
Thanks @TheSharpieOne
