### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by agraboso** [agraboso/redux-api-middleware#124]
I don't have time to maintain this package, yet it seems quite a few people do use it. If you are willing to take on the maintainer role, let me know here.

**Comment by nason** [comment]
Hey @agraboso, I'm interested

**Comment by agraboso** [comment]
@nason I'm on vacation until Sunday. Send me an email to agraboso@gmail.com and I'll contact you on Monday.

**Comment by olslash** [comment]
is this moving forward? do we have a maintainer!? 

I'd also be down to help as time allows. I've got a fork where I've merged the existing PRs and made some changes so I'm fairly familiar with the codebase.

Let's get this thing stable again!

**Comment by agraboso** [comment]
Just to let everybody know: we have a new maintainer! Give a warm welcome to @nason!

**Comment by f0urfingeredfish** [comment]
Welcome @nason. If you need any help I am available. We use this extensively at submittable and would like to see it maintained.
