### ISSUE TITLE
Actions may not have an undefined "type" property. Have you misspelled a constant?

### ISSUE THREAD

**Issue by khotey** [agraboso/redux-api-middleware#133]
Use redux-api-middleware@next

CreateStore:
```
import { applyMiddleware, createStore, compose } from 'redux'
import thunk from 'redux-thunk';
import { createLogger } from 'redux-logger'
import { apiMiddleware } from 'redux-api-middleware';
import createReducer from './reducers'

// TODO: create inject reducer function for local reducers
const middlewares = [
  apiMiddleware,
  thunk,
  createLogger(),
]
const createStoreWithMiddleware = applyMiddleware(...middlewares)(createStore)

export default (initialState = {}) => createStoreWithMiddleware(createReducer(), initialState)
```

./reducers:

```
import { combineReducers } from 'redux'

import reducers from '../reducers'

export const makeRootReducer = () => combineReducers({
  ...reducers,
})

export default makeRootReducer
```

actionCreator: 
```
function signIn(data) {
  return {
    [CALL_API]: {
      endpoint: `${apiUrl}/sign-in`,
      method: 'POST',
      types: [
        SIGN_IN.REQUEST,
        SIGN_IN.SUCCESS,
        SIGN_IN.FAILURE,
      ]
    }
  }
```
}

**Comment by khotey** [comment]
changed CALL_API to RSAA

**Comment by chidionuekwusi** [comment]
How exactly did you solve this issue ?

**Comment by khotey** [comment]
RSAA is a new alias to CALL_AP
import { RSAA } ...

**Comment by andresilveira** [comment]
@chidionuekwusi @ghost sorry for reviving the thread. But could you guys solve this issue? I've updated `CALL_API` to `RSAA`. But the problem remains.

**Comment by Mazzuchetti** [comment]
https://stackoverflow.com/questions/42749353/actions-may-not-have-an-undefined-type-property-have-you-misspelled-a-constan 

her is the solution

**Comment by bilalmajeed64** [comment]
import EMPLOYEE_UPDATE from './types';

export const employeeUpdate = ({ prop, value }) => {
        return {
            type: EMPLOYEE_UPDATE,
              payload: { prop, value }
            };
};

     //another class
 
value={this.props.name}
                onChangeText={value => this.props.employeeUpdate({ prop: 'name', value })}

**Comment by anton6** [comment]
I still don't understand how this works because:

```
[CALL_API]: {
    endpoint: `${apiUrl}/sign-in`,
    method: 'POST',
    types: [
      SIGN_IN.REQUEST,
      SIGN_IN.SUCCESS,
      SIGN_IN.FAILURE,
    ]
}
```

does not contain **type**

Why does it not throw: "Uncaught (in promise) Error: Actions may not have an undefined "type" property. Have you misspelled a constant?"

Can someone please clarify?

Thanks

**Comment by Ratandeep123** [comment]
Error:Actions may not have undefined type property "type" property.have you misspelled a constant

**Comment by NehaSachan** [comment]
Hey
It should be "type" not "types" in

actionCreator:

function signIn(data) {
  return {
    [CALL_API]: {
      endpoint: `${apiUrl}/sign-in`,
      method: 'POST',
      **_types_**: [
        SIGN_IN.REQUEST,
        SIGN_IN.SUCCESS,
        SIGN_IN.FAILURE,
      ]
    }
  }

**Comment by ambhuj-bit** [comment]
Error: Actions may not have an undefined "type" property. Have you misspelled a constant?


 const dispatch = useDispatch();
  const product = useSelector((state) => state.post.data);
  const { id } = useParams();
  useEffect(() => {
    loadPost();
  }, []);

  const loadPost = () => {
    dispatch(getPost(id));
  };

  if (!product) {
    return <h1>loading..</h1>;
  }
 

please help
