### ISSUE TITLE
Unable to use getJSON in meta and payload descriptor functions

### ISSUE THREAD

**Issue by marceux** [agraboso/redux-api-middleware#134]
The documentation has the following example on how to read from the `res` Object within the `payload` descriptor.

```javascript
{
  type: 'SUCCESS',
  payload: (action, state, res) => {
    const contentType = res.headers.get('Content-Type');
    if (contentType && ~contentType.indexOf('json')) {
      // Just making sure res.json() does not raise an error
      return res.json().then((json) => normalize(json, { users: arrayOf(userSchema) }));
    }
  }
}
```

This is great and works perfectly. But when I want to include similar functionality for `meta`, I encounter an `InternalError: already read` using the following JSON response and descriptors definition.

```json
{
  "data": [1, 2, 3, 4],
  "url": "http://api.target.com/data"
}
```

```javascript
// Descriptors Code Example
{
  type: 'SUCCESS',
  meta: (action, state, res) => {
    return getJSON(res).then((json) => omit(json, 'data'))
  },
  payload: (action, state, res) => {
    return getJSON(res).then((json) => omit(json, 'url'));
  }
}
```

*Note: I use `getJSON`, but that simply wraps the `Response.json()` method.*

The middleware's [`actionWith()`](https://github.com/agraboso/redux-api-middleware/blob/master/src/util.js#L69-L94) function calls the `payload` descriptor first, and then calls the `meta` descriptor. This means that the `meta` descriptor throws the `InternalError` because it attempts to read from the `Response` Object's `body` property after it has already been read by the `payload` descriptor.

Is there a way around this using your middleware? Is there a proposed change in the works?

Any help is appreciated, thanks.

For more reading and a similar example, you can look at [this](https://stackoverflow.com/a/35000918/1836846) StackOverflow question.

**Comment by nason** [comment]
Hi @marceux,

I've run into this issue too. This happens because the body of a Response object can only be read once. I've used the [`Response#clone`](https://developer.mozilla.org/en-US/docs/Web/API/Response/clone) method  to use the response in both payload and meta 

> In fact, the main reason clone() exists is to allow multiple uses of Body objects (when they are one-use only.)

Note that you'll need to do this in both `payload` and `meta` to get fresh Response objects for each. My RSAA looks something like:

```js
types: [
  { type: REQUEST, meta },
  {
    type: REQUEST_SUCCESS,
    payload: (action, state, res) => {
      const payloadResponse = res.clone();
      return getJSON(payloadResponse).then(json => ({
        data: json,
        result: parseData(json),
      }));
    },
    meta: (action, state, res) => {
      // fire analytics conditionally whenever result is computed with a 'shouldEmit' value
      // note this is derived from the response body and `res` must be cloned before reading 
      // from it both here and above in payload
      const metaResponse = res.clone();
      return getJSON(metaResponse).then(json => {
        const { shouldEmit, event } = parseData(json);

        if (!shouldEmit) {
          return meta;
        }

        // Meta + analytics
        return {
          analytics: {
            type: TRACK,
            payload: { ... },
          },
          // Merged into action meta
          ...meta,
        };
      });
    },
  },
  { type: REQUEST_FAIL, meta },
]

```

Can you try something like that out?

**Comment by marceux** [comment]
Hi @nason,

Thanks for responding and thanks for the assistance. I was about to submit a pull request to avoid cloning like this, but this will work just.

Cheers.

**Comment by nason** [comment]
Great! Closing for now but feel free to re-open if this continues to be an issue

**Comment by iamandrewluca** [comment]
Create own `getJSON`
```js
import { getJSON as noCloneGetJSON } from 'redux-api-middleware'

export function getJSON(res) {
  return noCloneGetJSON(res.clone())
}
```
