### ISSUE TITLE
Testing with nock returns network request failed.

### ISSUE THREAD

**Issue by koox00** [agraboso/redux-api-middleware#136]
Hi,  
no matter the url I use to `nock` I always get `REQUEST` action dispatched twice,  
once with `meta`, `payload` as undefined and once with `error: true` and `payload:[RequestError: Network request failed]` .  

Is there any solution to this? or something that I can do to debug it?  

```js
  it("creates FETCH_FILES_SUCCESS when fetching files has been done", () => {
    nock("http://localhost:3000/")
      .get("/jessica/hyde/files")
      .reply(200, { data: []});

    const expectedActions = [
      { type: types.FETCH_FILES_REQUEST, meta: undefined, payload: undefined },
      {
        type: types.FETCH_FILES_SUCCESS,
        meta: undefined,
        payload: {
          entities: {},
          result: {}
        }
      }
    ];

    const store = mockStore({ files: []});

    return store
      .dispatch(
        actions.loadFiles({
          user: { data: { username: "jessica" } },
          slug: "hyde"
        })
      )
      .then(() => {
        // return of async actions
        expect(store.getActions()).toEqual(expectedActions);
      });
  });
```

(awesome plugin though, really appreciate it :) )

Using the `next` branch.

**Comment by nason** [comment]
Hi @koox00, 

This package's tests use nock themselves -- see https://github.com/agraboso/redux-api-middleware/blob/next/test/index.js#L1270 for reference.

I think you need to set a content type on the mocked response: `.reply(200, { data: []}, { 'Content-Type': 'application/json' })`, but I don't know enough about your project/setup to help much more. If you can't resolve it, a simple demo repo might help debug

**Comment by koox00** [comment]
Thank you @nason , I will also try stackoverflow as it is more appropriate.  

The second thing is that instead of a `FAILURE` type action on the network failure, a `REQUEST` type gets dispatched with `error:true`. I will try to reproduce it in a demo repo over the weekend and post my findings

**Comment by koox00** [comment]
I've made a demo repo with just one test and one action. It fails with the same error.  
Can you check it out: https://github.com/koox00/redux-api-middleware-simple-case

**Comment by nason** [comment]
Hi @koox00, thanks that made things a lot simpler! In your case, it looks like the request is failing due to CORS checks. Changing the nock setup to look like

```diff
    nock("https://api.github.com")
      .get("/users/jessicahyde")
      .reply(200, {
        data: { id: "id" },
      }, {
+        'Access-Control-Allow-Origin': '*',
        'Content-type': 'application/json'
      });
```

Gets the test to pass for me.

---------

Another option that's new in `2.0`/`next` is the ability to mock global `fetch`. That would look more like:

```
const mockResponse = (status, statusText, response) => {
  return new window.Response(response, {
    status: status,
    statusText: statusText,
    headers: {
      'Content-type': 'application/json'
    }
  });
};

window.fetch = jest.fn().mockImplementation(() =>
  Promise.resolve(mockResponse(200, null, JSON.stringify({data: { id: "id" }}))));

```

Instead of `nock`, and would avoid hitting the network layer entirely.

Hope that helps resolve your issue!

**Comment by koox00** [comment]
Yeap that did the trick in the demo! 

Not in my real app though. Seems that something else is missing too. 
It would be super nice if we could have more detailed errors.

e.g: 
nock without using the middleware informs that the expected url didn't match the actual one, using the middleware we only get `Network request failed`.

Anyway mocking jest did the trick !!

**Comment by AllenFang** [comment]
Thanks @nason's answer, it's also work for me 👍
