### ISSUE TITLE
npm run test: Error

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [agraboso/redux-api-middleware#137]
Hello, 

If I try to run `npm run test` I get the following error:

```
/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
```
Does somebody know how to fix it?

Cheers,

Francesco Saverio

**Comment by nason** [comment]
I'm having no luck reproducing on the `master` or `next` branch. Closing, but feel free to re-open if this is still an issue.
