### ISSUE TITLE
Does'nt work in MS Edge in case pass body: null with GET query

### ISSUE THREAD

**Issue by greenteamsite** [agraboso/redux-api-middleware#138]
The next code returns the error only in Microsoft Edge - 'Failed to execute 'fetch()' on 'Window': HEAD or GET Requests cannot have a body.'

```
[CALL_API]: {
    endpoint: 'http://www.example.com/api/users',
    method: 'GET',
    body: null, // or some data
    types: ['REQUEST', 'SUCCESS', 'FAILURE']
  }
```

**Comment by nason** [comment]
Thanks for reporting.

I can reproduce in Edge 15 by running the following:

```js
fetch('https://www.google.com', { method: 'GET', body: null });
```

Interestingly, this does _not_ cause the same error and works fine:

```js
fetch('https://www.google.com', { method: 'GET', body: undefined });
```

This will require an update to https://github.com/agraboso/redux-api-middleware/blob/next/src/middleware.js#L102 to be more defensive when assembling options for the `fetch` call.

This bug makes me think we should set up some browser tests to catch inconsistencies like this one!
