### ISSUE TITLE
RequestError: undefined is not an object

### ISSUE THREAD

**Issue by hamxabaig** [agraboso/redux-api-middleware#140]
Hey, We've an issue here with sending request. It works fine on Android and Desktop browsers (even Safari) but doesn't work in iOS Safari, neither Chrome nor Firefox.

Following is the code to send request, it basically fetches the fund info of user so therefore `credentials: include` is added so that it sends the cookie to the server.

```javascript
export const getFundInfo = () => (dispatch, getState) => {
  return dispatch({
    [CALL_API]: {
      endpoint: `${BASE_URL}/fundInfo`,
      method: 'POST',
      credentials: 'include',
      types: [
        REQUEST_GET_FUND_INFO,
        RECEIVE_GET_FUND_INFO,
        FAILURE_GET_FUND_INFO,
      ],
    }
  });
};
```
But instead of returning error or success from API. It fires up `REQUEST_GET_FUND_INFO` type again with `payload` as in screenshot below:
<img width="764" alt="screen shot 2017-07-23 at 2 22 27 pm" src="https://user-images.githubusercontent.com/12872177/28498198-6dafa654-6fb2-11e7-9f3e-36075fa7a6cf.png">

I tried with `window.fetch` of browser in Safari iOS and it works fine with that request. I think this maybe a problem with this library or fetch library which you guys using. Was not sure where to start so filed an issue here.

Thanks

**Comment by indrasantosa** [comment]
Hey @hamxabaig,
What request are you making to the server?
Is it a "POST" request without a body?

**Comment by hamxabaig** [comment]
@indrasantosa that's correct. POST request without body.

**Comment by indrasantosa** [comment]
I never tried sending an empty post before, maybe defining an empty object for the body might worth a try

**Comment by hamxabaig** [comment]
@indrasantosa i investigated the issue, it was issue with `headers` being undefined instead of an object. In my test case, you can see there are no `headers` defined thats why it was freaking out. I just added empty headers object and it worked fine.

However seeing [this line of code](https://github.com/agraboso/redux-api-middleware/blob/master/src/middleware.js#L102) makes me wonder why. Seems babel isn't transpiling this into correct form.

I went to `node_modules/redux-api-middleware` and modified it there using `headers || {}` and it worked fine also.

So i believe there is something problem with that.

**Comment by indrasantosa** [comment]
Ahh, I get that now. But it could be not a Babel trans-piling issue.

The links indicate that there was a fix that added a default value headers if headers do not exist, and you've done on yours too. So, I think it might be just a version issue?

**Comment by hamxabaig** [comment]
@indrasantosa ah I think you're right. Someone already fixed on the `middleware.js` in `v1.0.3` and i was using `v1.0.2` and i didn't thought of it LMAO 🤣 
Thanks by the way, closing now.

**Comment by indrasantosa** [comment]
No worries, glad that you found it @hamxabaig 😄
