### ISSUE TITLE
Bug with next branch and Safari

### ISSUE THREAD

**Issue by georgemoon** [agraboso/redux-api-middleware#144]
Using redux-api-middleware with whatwg-fetch (the default with create-react-app) fails on Safari. 

On further investigation into the transpiled code, it appears that this is due to a TypeError on the fetch call (about undefined parameters). After forking the ES6 code and making it comply with prettifier, it appears that adding `headers: headers || {}` (as was the case in v1.x.x) makes it work properly.

See commit on my fork of the code: https://github.com/georgemoon/redux-api-middleware/commit/c802ac6ce629f05f9c704f33032d8c0ed8f82de5

**Comment by nason** [comment]
Thanks for reporting! This must have slipped through the cracks somehow.

**Comment by nason** [comment]
Fixed and released as `2.0.0-beta.3`
