### ISSUE TITLE
Breaking changes with v2 ?

### ISSUE THREAD

**Issue by amangeot** [agraboso/redux-api-middleware#147]
Hello,
I had some issues with IE11 not being able to read `CALL_API` `Symbol` so I upgraded to v2.

It looks like it's working fine, is there any breaking change coming with v2 ?

**Comment by nason** [comment]
Hi @amangeot, the main other thing with 2.0 is that you'll need to bring your own `fetch` -- this package no longer polyfills `fetch` and expects it to be available on the global scope.

https://github.com/agraboso/redux-api-middleware/releases/tag/v2.0.0 has the full release notes
