### ISSUE TITLE
ApiError

### ISSUE THREAD

**Issue by svenvanlierde** [agraboso/redux-api-middleware#164]
When i use this libraray for 'post', I always get an ApiError..
my code:

<img width="722" alt="screen shot 2018-01-16 at 18 44 23" src="https://user-images.githubusercontent.com/24588562/35003659-bec45924-faed-11e7-85ad-3db3975f17ea.png">

error in console:
<img width="486" alt="screen shot 2018-01-16 at 18 44 46" src="https://user-images.githubusercontent.com/24588562/35003676-c8951664-faed-11e7-9044-1abfc69ae6ad.png">

Al my GET requests are working fine ?
Any ideas ? 
Thanks

**Comment by agraboso** [comment]
The server is returning a 500. Does this not happen if you make a POST request by any other means?

**Comment by svenvanlierde** [comment]
Hello,

With a 'fetch' POST everything works fine.
With the library al GETS are good, POSTS not :(

my old  fetch post code:
<img width="410" alt="screen shot 2018-01-16 at 21 14 35" src="https://user-images.githubusercontent.com/24588562/35010195-64964768-fb02-11e7-9d72-eaaef61366dd.png">


I've no idea what i'm doing wrong ..

Thx

**Comment by nason** [comment]
Hi @svenvanlierde!

A couple thoughts:

1. Can you see the request happening in your browser devtools? If you do see a bad request there, that's a good starting point. If so, you could compare the request that this middleware is making vs a request by calling `fetch` directly and see if there are any differences (there shouldn't be)

2. Whats going on in the `onVehicleListBidSuccess` function? Are you sure that's not throwing? It looks like you're passing `dispatch` to it, which isn't defined in the snippet you shared.

**Comment by svenvanlierde** [comment]
Hi,
little update:
code works in reactjs web project (GET AND POSTS)
code does not work in react native project (GET works, Post not) :(

reactjs and react native use same codebase ...

**Comment by nason** [comment]
Oh interesting. I don't have much experience with react-native, but the devtools should be handy. Can you see the failing request there? And would it make any difference if you used an absolute url for the request?

**Comment by svenvanlierde** [comment]
Hello, 

Problem is solved. With 'Reactotron' i could get a more detailed error why the api call failed in react-native => A wrong body causes api failure.

A more detailed error in console would be nice, instead of ApiError - undefined.

Thanks for tips & help everybody

Grtz

**Comment by agraboso** [comment]
@svenvanlierde `ApiError` simply wraps the response from the server &mdash; in your case, the server was responding with status code 500, status text `500 - undefined` and an empty body &mdash;, so I don't see how we could provide any more info in the console. Glad you found the problem though.

**Comment by mightym** [comment]
@svenvanlierde @agraboso this has to do with react native. Though I have no clue why, but I checked my post request on a browser based client, with http://httpie.org and a react native client. The first both return:

a 400 with:
```
{
    "description": [
        "This field is required."
    ]
}
```
with react native and redux-api-middleware I get this:
```
Object {
  "error": true,
  "meta": undefined,
  "payload": [ApiError: 400 - undefined],
  "type": "CREATE_FAILURE",
}
```
no matter what I do: the payload is always ` [ApiError: 400 - undefined],` for a 400 response and  [ApiError: 500 - undefined], for a 500 response
