### ISSUE TITLE
Connection Refused Breaks Redux

### ISSUE THREAD

**Issue by awjreynolds** [agraboso/redux-api-middleware#180]
I have a scenario where you can 'break' the redux store within an application by loading the React/Redux/Router client then killing the API which generates an unhandled error from the fetch as Connection Refused within the api middleware. 

"GET http://localhost:3000/api/context/refresh net::ERR_CONNECTION_REFUSED" 

I think this is down to this line of code. 
https://github.com/agraboso/redux-api-middleware/blob/6bf1a810935addca2a82636b47ada625073a95b6/src/middleware.js#L166

As redux is broken at this point, the application becomes unresponsive (i.e. cannot switch pages etc).

**Comment by nason** [comment]
Hi @awjreynolds can you be any more specific please?

The line you linked to is in a catch block that should handle an error while fetching and prevent propagation of errors coming from the request itself.

**Comment by awjreynolds** [comment]
Hi @nason,
I may have the line wrong. What I was trying to highlight is that if you 'break' the connection to the backend API and get a connection refused, then the api breaks redux as redux gets an unhandled exception. I'm really up against it ATM but will try and get a simple example built. If you have an app with this middleware that is using a remote API, just fire it up, then turn off your wifi to see the error.

**Comment by explosivose** [comment]
I work with @awjreynolds and we found that our application state was being helpfully updated by a regular heartbeat which we decided to remove. Once we removed that we realised it was the heartbeat masking a state management & routing issue in our code. So this is not an issue with redux-api-middleware after all! This can be closed

**Comment by samcole1992** [comment]
What do you mean by heartbeat?

**Comment by nason** [comment]
Thanks for the update @explosivose. I'll close this, sounds like an interesting issue though!
