### ISSUE TITLE
redux-api-middleware /  thunk middleware order

### ISSUE THREAD

**Issue by EricFries** [agraboso/redux-api-middleware#181]
When using with thunk, does the order that these are passed to `applyMiddleware` matter?  

I've seen it as both `applyMiddleware(thunk, apiMiddleware)` and `applyMiddleware(apiMiddleware, thunk)`.  Is there a best practice?

**Comment by EricFries** [comment]
@nishantsinha-5 Great, thanks for the clarification.

**Comment by codfish** [comment]
@EricFries @nishant-labs @agraboso, I can't ever seem to get it working the way the example shows: 
https://github.com/agraboso/redux-api-middleware#dispatching-thunks

In my situation, i would like to actually get feedback in the component on the response of the request and enable/disable forms while waiting for a response from the server.

I can never get this to work and I'm not sure why or what I'm doing wrong. In trying to get it working in conjunction with thunk it just won't wait for a response as if rsaa isn't returning a promise.

```js
export const createThing = (values) => async (
  dispatch,
  // getState,
) => {
  const actionResponse = await dispatch(
    createAction({
      endpoint: `${apiUrl}/things`,
      method: 'POST',
      body: JSON.stringify(values),
      types: [CREATE_THING_REQUEST, CREATE_THING_SUCCESS, CREATE_THING_FAILURE],
    }),
  );

  console.log(actionResponse);
};
```

My middleware order:

```js
const middlewares = [
  // ...
  apiMiddleware,
  thunk,
  // ...
];
```

`actionResponse` is always `undefined` and logs out _immediately_ before a response comes back. Am I doing something wrong?

If you want me to create a new issue for this you can, I couldn't find an issue that covered exactly this.

**Comment by iamandrewluca** [comment]
@codfish If you don't need anything from store you can dispatch without using a thunk.

Try this

```js
export const createThing = (values) => (
  dispatch,
  // getState,
) => {
  return dispatch(
    createAction({
      endpoint: `${apiUrl}/things`,
      method: 'POST',
      body: JSON.stringify(values),
      types: [CREATE_THING_REQUEST, CREATE_THING_SUCCESS, CREATE_THING_FAILURE],
    }),
  );
};
```
```js
const action = await dispatch(createThung({}))
```

**Comment by codfish** [comment]
@iamandrewluca thanks! I updated my original comment with the reason I found it wasn't working at all. I was also able to simplify it to be the following:

```js
export const editThing = (values) =>
  createAction({
    endpoint: `${apiUrl}/things`,
    method: 'POST',
    body: JSON.stringify(values),
    types: [EDIT_THING_REQUEST, EDIT_THING_SUCCESS, EDIT_THING_FAILURE]
  });
```

Then in my component:

```js
onSubmit: async values => {
  const result = await dispatch(editThing(values));
  if (!result.error) setEditMode(false);
  return result;
},
```

It's still working even without making the action creator return a thunk. I was kinda surprised by this but i guess this makes sense right?
