### ISSUE TITLE
Is it possible to set default headers?

### ISSUE THREAD

**Issue by bexoss** [agraboso/redux-api-middleware#182]
I am trying to use jsonwebtoken, so I want to set headers like `Authorization': `Bearer ${localStorage.jwt}`. How can I do it? If I use **axios**, then I can do this with interceptor, but your library use **fetch**, so I don't know how to implement to this. 

reference: https://stackoverflow.com/questions/44820568/set-default-header-for-every-fetch-request

Do you guys have any idea?

**Comment by nason** [comment]
Not exactly _default_ but one way is to look it up when creating your `RSAA` and passing a custom headers property: https://github.com/agraboso/redux-api-middleware#rsaaheaders

Here is a basic example:

```js
{
  [RSAA]: {
    ...
    headers: {
      Authorization: `Bearer ${localStorage.getItem('jwt')}` 
    }
    ...
  }
}
```

Does that help?

Once #171 is done, you'll be able to create a middleware with defaults. I think you could set defaults for requests invoked via this middleware by providing a custom `fetch`. Something like https://github.com/moll/js-fetch-defaults

**Comment by darthrellimnad** [comment]
You could also achieve the same type of "interceptor" functionality with normal `fetch` behavior by adding your own middleware, before apiMiddleware in the chain.  Here, you could test the action with `isRSAA`, handle it as necessary, or ignore, then pass action to next middleware.  Your "auth middleware" can then be setup to dynamically apply headers to RSAAs as they get dispatched :)

**Comment by marcin-piela** [comment]
If you don't want to write it by yourself check-out this simple package 
https://github.com/TheSoftwareHouse/react-packages/tree/master/packages/redux-api-auth-middleware

**Comment by hamxabaig** [comment]
If anyone looking for an interceptor that intercepts all API calls made with `redux-api-middleware` then this might be of some help:
https://github.com/hamxabaig/redux-api-middleware-interceptor

**Comment by iamandrewluca** [comment]
With `v3.x` you can pass your own fetch function. And can customize anything about request.

```js
// ...
import { createMiddleware } from 'redux-api-middleware'

const apiMiddleware = createMiddleware({ fetch: customFetch })
const store = createStore(reduce, applyMiddleware(apiMiddleware))

function customFetch(uri, options = {}) {
  return fetch(uri, {
    ...options,
    headers: {
      ...options.headers,
      Authorization: `Bearer ${localStorage.getItem('jwt')}`
    }
  })
}
```
