### ISSUE TITLE
Typings/declaration files for use with TypeScript 

### ISSUE THREAD

**Issue by jamalsoueidan** [agraboso/redux-api-middleware#184]
Where do I find typing for redux-api-middleware?

```javascript
export interface ILoadUsers extends RSAAction<LOAD_USERS_REQUEST, LOAD_USERS_SUCCESS, LOAD_USERS_FAILURE> {}

export const LoadUsers: ActionCreator<ILoadUsers> = () => ({
  [RSAA]: {
    types: [Types.LOAD_USERS_REQUEST, Types.LOAD_USERS_SUCCESS, Types.LOAD_USERS_FAILURE],
    endpoint: '/dist/users.json',
    method: 'GET'
  }
})
```

This throws error later when using as dispatcher.

```javascript
export type DispatchActions = Users.Types.ILoadUsers

const mapDispatchToProps = (dispatch:Dispatch<DispatchActions>) => ({
  loadUsers: () => dispatch(Users.Actions.LoadUsers()),...
```

How to solve this? Did anyone solve it?

@types
```javascript
declare module 'redux-api-middleware' {
    import {Middleware} from "redux";

    export const RSAA: string;
    export const apiMiddleware: Middleware;

    export type HTTPVerb = 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS';

    export interface RSAAction<R, S, F> {
        [propName: string]: { // Symbol as object key seems impossible
            endpoint: string;  // or function
            method: HTTPVerb;
            body?: any;
            headers?: { [propName: string]: string }; // or function
            credentials?: 'omit' | 'same-origin' | 'include';
            bailout?: boolean; // or function
            types: [R, S, F];
        }
    }
}
```

Error:
`
{
	"resource": "/c:/testerne/src/Pages/Application/index.tsx",
	"owner": "typescript",
	"code": "2344",
	"severity": 8,
	"message": "Type 'Actions' does not satisfy the constraint 'Action<any>'.\n  Type 'ILoadMessage' is not assignable to type 'Action<any>'.\n    Property 'type' is missing in type 'ILoadMessage'.",
	"source": "ts",
	"startLineNumber": 21,
	"startColumn": 47,
	"endLineNumber": 21,
	"endColumn": 54
}
`

**Comment by Madebyfen** [comment]
Hey, I'm brand new to TS, but in the process of converting some custom interceptor middleware that sits in front of `redux-api-middleware`.

If you extend from Redux's `AnyAction` type, you can use the RSAAction type in `next()`, and I presume therefore `dispatch()`:

```TypeScript
import { Middleware, AnyAction } from 'redux';
// ...
export interface RSAAction<R, S, F> extends AnyAction {
// ...
```

```Typescript
next(action: RSAAction); // (or `dispatch()`)
```

Hope that's useful!

**Comment by darthrellimnad** [comment]
I think the problem might be with your type for your ActionCreator function?
> `export const LoadUsers: ActionCreator<ILoadUsers> = () => ({ ... })`

Can't be sure with info provided, but does the `ActionCreator` type expect to return an FSA? The Error message seems to indicate that there is a missing `type` property, which an RSAA won't have (only the `RSAA` property on the top level object).

If you made a new type for an `RSAAActionCreator` that expects to return a valid RSAA, would that resolve the issue?

**Comment by iamandrewluca** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36666

**Comment by iamandrewluca** [comment]
@nason I think this can be closed.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-api-middleware

**Comment by jamalsoueidan** [comment]
Thank you :)

**Comment by tevonsb** [comment]
Requesting to reopen! Looks like the types in definitelyTyped have fallen behind the current version. 

There is no definition for `createAction`. Is anyone else running into this or am I missing something?

If other people are experiencing, I'll dig in and put up a PR for the type. Currently just bypassing my not using `createAction`, sad :(

**Comment by iamandrewluca** [comment]
You can open a PR in `definitelyTyped` and fix this.  
In the feature I will try keep types in sync with all changes

**Comment by magoogli** [comment]
@tevonsb I am experiencing the same problem... How did you work around it?

**Comment by iamandrewluca** [comment]
Today I'll make a fix in def typed.
