### ISSUE TITLE
The release of 1.0.0-beta3 may not be built correctly

### ISSUE THREAD

**Issue by riophae** [agraboso/redux-api-middleware#19]
The release of 1.0.0-beta3 from npmjs.org may be wrong built. It doesn't support `credentials` option at all, since that key was considered illegal.

<img width="991" alt="screen shot 2015-11-04 at 20 07 31" src="https://cloud.githubusercontent.com/assets/1289884/10937709/c2432482-832f-11e5-93fa-60d4718ce1ec.png">

I cloned the repo & built it myself. Everything works fine now.

**Comment by ericmash** [comment]
The release in npm definitely has some issues. 

https://github.com/agraboso/redux-api-middleware/issues/28 is fixed if this project is built locally.

**Comment by barrystaes** [comment]
Does this problem with using `credentials` still exist?

**Comment by barrystaes** [comment]
I no longer see riophae's fork, and from #28 i gather that this problem no longer exists with 1.0.0-beta3.
