### ISSUE TITLE
import doesn't work in pure es6 modules

### ISSUE THREAD

**Issue by ranjeet-choudhary** [agraboso/redux-api-middleware#196]
(index):1 Uncaught SyntaxError: The requested module '../../../node_modules/redux-api-middleware/lib/index.js' does not provide an export named 'RSAA'
had to fork https://github.com/agraboso/redux-api-middleware/tree/next and remove "lodash.isplainobject": "^4.0.6" which is in es5.
can it be replaced with es6?

**Comment by ranjeet-choudhary** [comment]
@nason 
This the setup i have https://github.com/Polymer/pwa-starter-kit
import {RSAA} from 'redux-api-middleware/es'  works only if i remove only if i remove lodash.isplainobject from https://github.com/agraboso/redux-api-middleware/blob/next/src/validation.js#L2 and replace with es6 module

**Comment by nason** [comment]
Thanks for the detail @ranjeet-choudhary! I'll work on getting this cleaned up next for the 3.0 beta

**Comment by nason** [comment]
3.0.0-beta.2 was released with some of the changes you suggested, so I'm going to close this out. Feel free to re-open if this continues to be a problem
