### ISSUE TITLE
How to chain actions?

### ISSUE THREAD

**Issue by mohanzhang** [agraboso/redux-api-middleware#2]
With [redux-thunk](https://github.com/gaearon/redux-thunk) and explicit calls to the api via your favorite http library (fetch, qwest, etc), it was possible to dispatch other actions in response to an api call succeeding or failing. What is the corresponding technique with redux-api-middleware?

The naive solution would be to allow additional fields on the action object, e.g. `onSuccess` and `onFailure` that give you the same inversion of control that redux-thunk does, but I am still very new to this ecosystem, so I am not sure if this is the preferred design pattern.

Another possibility would be some way to observe the redux state and react to changes out-of-band. That way, on `MY_ACTION.SUCCESS`, I could set the dirty flag in the state, thus causing a new action to be emitted by an observer that was monitoring this state. I feel like I am on the verge of describing [redux-rx](https://github.com/acdlite/redux-rx), but I have not fully integrated the ideas behind FRP yet, so I am just saying words at this point.

Any wisdom on this topic would be greatly appreciated :)

**Comment by agraboso** [comment]
Something along the lines of your third paragraph is what I would do using `redux-api-middleware`. The `redux` ecosystem is evolving rapidly, and I am sure a better, more flexible way of dealing with API calls will be devised. `redux-api-middleware` is rather rigid, but it serves a purpose.

**Comment by mohanzhang** [comment]
In case anyone else stumbled upon this thread wondering the same thing, here's how easy it was to use redux-rx (I created a file called `observeStore.js`):

```js
import { observableFromStore } from 'redux-rx';

import * as actions from '../actions';

export default function observeStore(store) {
  const stateStream = observableFromStore(store);

  stateStream
    .distinctUntilChanged(state => state.users.isStale)
    .filter(state => state.users.isStale)
    .subscribe(() => {
      store.dispatch(actions.fetchUsers());
    });

  return store;
}
```

In `Root.js` "smart container":

```js
import configureStore from '../store/configureStore';
import observeStore from '../store/observeStore';

const store = observeStore(configureStore());
```

Now whenever *any* reducer sets `state.clients.isStale` to `true`, then it will instantly react with a fetch from the server. So sweet! Hope this helps someone.
