### ISSUE TITLE
Accept array to exec more then one call

### ISSUE THREAD

**Issue by LucaColonnello** [agraboso/redux-api-middleware#20]
Accept an array to perform more then one call, dispatch types for each call and for the queue.

**Comment by LucaColonnello** [comment]
Is it possible in this version or there's a way to make more then one call being notified when all are done?

**Comment by barrystaes** [comment]
I imagine you could add a tiny [middleware](http://rackt.org/redux/docs/advanced/Middleware.html#seven-examples) that 
- accepts an array of RSAA requests
- gets the 1st item using `unshift()` and pass this to `next()`
- dispatches the remaining array (using `dispatch()`) to repeat the cycle.
