### ISSUE TITLE
Throws "unhandled promise rejection" (umd build)

### ISSUE THREAD

**Issue by patlux** [agraboso/redux-api-middleware#212]
Hello everyone,

I tested the new v3 release and I found a issue with my code.

I have something like this in my code which has nothing to do with this library (I'm slowly migrating all my fetch-calls to this library):

```js
const fetchSomething = ()=> fetch()
    .then(response => {
      if (!response.ok) {
        const error = new Error(response.statusText);
        error.response = response;
        throw error;
      }
      return response.json();
    })
    .then(responseJson => {
      dispatch(createActionSuccess(responseJson));
      return responseJson;
    })
    .catch(error => {
      dispatch(createActionFailure(error)); 
      throw error; // <-- throwing the exception again to catch the exception in my components if needed
    });
```

And in a component I'm calling it like

```js
fetchSomething().then(responseJson => {});
```

This works fine in v2.3.0, but in the v3 release I'm receiving the following error because I don't handle the `catch` case:

![img_0b412f570eb2-1](https://user-images.githubusercontent.com/4481570/48343073-ad6b8d80-e671-11e8-80d3-f51d493d8b6c.jpeg)

Source of the exception:

<img width="954" alt="screenshot 2018-11-12 at 11 49 34" src="https://user-images.githubusercontent.com/4481570/48342838-11da1d00-e671-11e8-9cfc-8fc39a661bae.png">

What would be the proper way to fix this without adding to each call a empty `.catch`-block?
And why does the umd-library catches all exceptions?

**Comment by nason** [comment]
Hi @patlux,

Thanks for reporting.

The middleware itself does a pretty good job not throwing uncaught errors. To be fair though, I haven't tested the UMD build too deeply.

I'm not sure I understand how the `fetchSomething` snippet you provided has to do with this middleware. Are the `createActionSuccess` or `createActionFailure` functions returning `RSAA`s somehow?

This could be related to some kind of build issue. Happy to help and investigate but I think I need a little more context.

**Comment by patlux** [comment]
Hi @nason,

thats actually the problem: It has nothing to do with this library, but the UMD-build of this library handles all unhandled catch exceptions in my project and calls `console.error`.

The `fetchSomething` snippet is just a example how my not-yet-ready migrated fetch functions are working.

**Comment by nason** [comment]
Yikes. So you're seeing that just by including the UMD build on your page, its affecting unrelated promises elsewhere in your project?

That is...tricky. And super odd. I think the best way to proceed is to setup a minimal example to reproduce.

A few things to note:

- I wonder if this is somehow related to RN (I haven't worked with it for a while)
- Perhaps upgrading babel dependencies here will help (I just noticed that we're still using beta 7.0 releases here)

**Comment by jordenchang55** [comment]
Same here. And my situation was only happened when `Debug JS Remotely` was off.
Downgrade to 2.3.0 fix it.

**Comment by matuszeg** [comment]
I am also getting this error. Downgrading to 2.3.0 fixed it for me. 
This is the error I got. Dont know if it will help
![api-redux-error](https://user-images.githubusercontent.com/1823856/56262069-24c6a280-6092-11e9-9ab8-e50e1fc8d46b.PNG)
