### ISSUE TITLE
Tests example in Readme doesn't work in 3.0.1

### ISSUE THREAD

**Issue by GusevDV** [agraboso/redux-api-middleware#220]
Hello!
Test example in Readme doesn't work for me in redux-api-middleware 3.0.1. FetchMock not mocking request and server send real response. I tried to run the test in version 2.3.0 and the request was mocked.
How to fix it in version 3.0.1?

```js
import configureMockStore from "redux-mock-store"
import { apiMiddleware } from "redux-api-middleware"
import thunk from "redux-thunk"
import fetchMock from "fetch-mock"
 
import {getUser} from "./user"
 
const middlewares = [ thunk, apiMiddleware ]
const mockStore = configureMockStore(middlewares)
 
describe("async user actions", () => {
  afterEach(() => {
    fetchMock.reset()
    fetchMock.restore()
  })
 
  it("should dispatch USER_SUCCESS when getUser is called", () => {
    const store = mockStore({});
    const body = {
      email: "EMAIL",
      username: "USERNAME"
    }
   //fetchMock doesn't work in 3.0.1
    fetchMock.getOnce("https://hostname/api/users/", {body: body, headers: {"content-type": "application/json"}}) 
    const expectedActions = [
      {type: actions.USER_REQUEST},
      {type: actions.USER_SUCCESS, payload: body}
    ]
    return store.dispatch(actions.getUser()).then(() => {
      expect(store.getActions()).toEqual(expectedActions)
    })
  })
})
```

**Comment by valmassoi** [comment]
@GusevDV any luck?

**Comment by GusevDV** [comment]
@valmassoi No. This problem is still actual.

**Comment by katliger-h** [comment]
@GusevDV I faced the same issue and found this solution: https://stackoverflow.com/questions/60171894/fetch-mock-dont-work-in-version-3-2-0-redux-api-middleware-test
You need to add "fetch:fetch" inside the action creator.

**Comment by iamandrewluca** [comment]
Or set a global fetch, how we do in tests
```js
global.fetch = require('jest-fetch-mock')
```

**Comment by iamandrewluca** [comment]
Also in `v3.x` you can pass your own implementation.
```js
import { createMiddleware } from "redux-api-middleware"
const apiMiddleware = createMiddleware({ fetch: /* any fetch compilant library */ })
```

> By default fetch-mock assumes fetch is a global so no more setup is required once you’ve required fetch-mock.
> https://www.wheresrhys.co.uk/fetch-mock/#usageglobal-non-global

I'll close this for now, If issue still can't be solveable, feel free to to reopen it.
