### ISSUE TITLE
Interest in Supporting Axios?

### ISSUE THREAD

**Issue by sherl0cks** [agraboso/redux-api-middleware#224]
It would be nice to be able to introduce axios for global interceptors. Is there interest in a adding a feature to make axios an option, and but use fetch by default? There is currently no fetch adapter for axios. https://github.com/axios/axios/issues/1219

**Comment by nason** [comment]
Hi @sherl0cks,

Would passing in a custom `fetch` function to the middleware / RSAA that calls `axios` instead work for this use case? See https://github.com/agraboso/redux-api-middleware#createmiddlewareoptions or https://github.com/agraboso/redux-api-middleware#rsaafetch

**Comment by sherl0cks** [comment]
@nason given there is no fetch adapter out there, I'd have to write my own. At that point, it is just easier to write my own middleware, which is what I've done already.

**Comment by iamandrewluca** [comment]
@sherl0cks with the version `v3.x` we allow to customize the fetch function.
Also with the version `axios@0.7.0` they allow fetch like requests 
https://github.com/axios/axios/blob/master/CHANGELOG.md#070-sep-29-2015

```diff
// ...
import axios from 'axios'
-import { apiMiddleware } from 'redux-api-middleware'
+import { createMiddleware } from 'redux-api-middleware'

+const apiMiddleware = createMiddleware({ fetch: axios })

const store = createStore(reducer, applyMiddleware(apiMiddleware))
```

**Comment by mewben** [comment]
@iamandrewluca I tried axios using the code above but I got this error:
`res.headers.get is not a function`

Perhaps it's the way axios accesses the headers like this?
`res.headers['Content-Type']` not get

**Comment by iamandrewluca** [comment]
@mewben try to use `Headers` instead of object representation
https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers

**Comment by iamandrewluca** [comment]
It seems axios has a different response than `fetch` https://github.com/axios/axios#response-schema

```js
import redux from "redux";
import api from "redux-api-middleware";
import axios from 'axios'

const { createStore, applyMiddleware } = redux
const { createMiddleware, createAction } = api

function reducer(state, action) {
    console.log(action)
    return state
}

const apiMiddleware = createMiddleware({
    // map axios object type headers to `Headers`
    // because internaly `getJSON` of `redux-api-middleware` uses spec `Headers`
    // https://github.com/agraboso/redux-api-middleware/blob/master/src/util.js#L13
    // strange is that in node environemnt `Headers` does not exist
    // but no one complained
    fetch: (url, config) => axios(url, config).then(res => ({
        ...res,
        headers: new Headers(res.headers)
    })),
    // axios response does not have `ok`
    ok: res => res.status === 200
})

const store = createStore(reducer, applyMiddleware(apiMiddleware))

store.dispatch(createAction({
    endpoint: 'https://github.com',
    method: 'GET',
    types: ['REQUEST', 'SUCCESS', 'FAILURE']
}))

```

**Comment by sdd** [comment]
Thanks @iamandrewluca for the snippet.

I had to extend the adapter above:
* redux-api-middleware was attempting to call .json() on the response;
* Axios expects POST / PATCH bodies to be specified as config.data rather than config.body.

```javascript
const axiosAdapter = (url, config) => {
    if (config.headers['Content-Type'] === 'application/json' && typeof config.body === 'string') {
        config.data = JSON.parse(config.body);
    } else {
        config.data = config.body;
    }
    return axios(url, config).then(res => {
        return {
            ...res,
            headers: new Headers(res.headers),
            json: () => res.data,
        };
    });
};


const apiMiddleware = createMiddleware({
    fetch: axiosAdapter,
    // axios response does not have `ok`
    ok: res => res.status === 200
})
```
