### ISSUE TITLE
AMD loading?

### ISSUE THREAD

**Issue by MikeMcElroy** [agraboso/redux-api-middleware#23]
Would really like to try this out in my project, but AMD loading (`define([deps], factory)`) is a requirement of my environment.  Any advice for getting this to load in an AMD environment with little effort?

**Comment by MikeMcElroy** [comment]
Could really use some input here.  **bump**

**Comment by elijahsmith** [comment]
@agraboso to get this working with AMD, a UMD build version is required -- add webpack, add build steps to package.json to create dist versions, etc.  Would you be open to a PR that implements this?

**Comment by barrystaes** [comment]
What exactly would a UMD build version entail?
But yes i would look at your PR, if its just an extra file or two.

However i cant test AMD modules, i'm no expert.
