### ISSUE TITLE
Testing RSAA api calls

### ISSUE THREAD

**Issue by sudh-0** [agraboso/redux-api-middleware#242]
@nason 
So, I am trying to write test cases for api calls. I tried following the `readme` but the test-case is always getting `failed`. 
On giving relative url link, I am getting this, instead of `SUCCESS`:
```
      "error": true,
      "meta": undefined,
      "payload": [ApiError: 404 - Not Found],
      "type": "@@user/USER_FAILURE"
```

I also tried giving the full endpoint,  and got this:
```
        "error": true,
        "meta": undefined,
        "payload": [RequestError: Network request failed],
        "type": "@@user/USER_FAILURE"
```

~Is this a `redux-thunk` problem or is it something else? Isn't there any other way to mock `redux-api-middleware` actions?~

**UPDATE**
This is not a `redux-thunk` problem. I implemented a sample test case using `redux-thunk` and native `fetch` method and it worked perfectly in tests. 
Apparently, `redux-api-middleware` isn't able to do the network-request and I don't know why, in spite of using `fetch` internally.

**Comment by sudh-0** [comment]
**SOLVED**
---------------------
So I passed the `fetch: fetch` in my action creators i.e.
```
[RSAA]: {
    endpoint: "/something",
    ...
    fetch: fetch
}
```
and it worked.

**Comment by iamandrewluca** [comment]
@sudh-0 you can also pass a global `fetch` for all actions
Instead of `apiMiddleware` you can use `createMiddleware({ fetch })`

**Comment by guzzijones** [comment]
good gosh thanks for reporting this.  I just had the exact same issue.
