### ISSUE TITLE
Error with Customized Dispatched FSA in Redux Devtools

### ISSUE THREAD

**Issue by ericmash** [agraboso/redux-api-middleware#28]
Redux Devtools shows each action with the current state. It works perfectly when standard FSA are dispatched by redux-api-middleware. However, if a customized FSA is used, the browser will give the following error:

> Uncaught (in promise) Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {type, meta}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `LogMonitorAction`.
    at invariant (http://localhost:3000/vendor.js?0f4c127a85fd659d26ce:708:16)
    at traverseAllChildrenImpl (http://localhost:3000/vendor.js?0f4c127a85fd659d26ce:8181:24)

This error is a React rendering error when JSX receives an Object instead of a String for rendering. For standard FSA, action type is a string, devtool renders correctly:
```javascript
// working
[CALL_API]: { 
  endpoint: 'path/to/endpoint',
  method: 'GET',
  types: [ 'REQUEST', 'SUCCESS', 'FAILURE' ]
}
```
For customized FSA, action type becomes an object, devtool struggles:
```javascript
// failed with invariant violation error
[CALL_API]: {
  endpoint: 'path/to/endpoint',
  method: 'GET',
  types: [ // example from documentation
	 'REQUEST',
	 'SUCCESS', {
	  type: 'FAILURE',
	  meta: (action, state, res) => {
		if (res) {
		  return {
			status: res.status,
			statusText: res.statusText
		  };
		} else {
		  return {
			status: 'Network request failed'
		  };
		}
	  }
  }]
}
```

Disabling devtool will fix the error as well. I would like to know
1. Is this the correct way of using customized FSA in redux-api-middleware?
2. Is there a workaround to get customized FSA and redux-devtools working together?
3. If this is a defect, is it an issue in redux-api-middleware or redux-devtools?

**Comment by ericmash** [comment]
This is related to https://github.com/agraboso/redux-api-middleware/issues/19.

I clone the repository and build the project locally, then the error is fixed. I am going to close this issue, and comment on the build issue.

I will log another issue that one test does not run correctly on Windows.

**Comment by riophae** [comment]
If the error gets fixed after building the project locally, I think you are doing it right.
The release in npm seems to be an outdated version of the project. It's not completely compatible with the current Fetch API spec, as I has described in #19.

**Comment by neverfox** [comment]
@ericmash @riophae Are you possibly running 0.6.x? If I install with `^1.0.0-beta3,` I stop getting this.

**Comment by riophae** [comment]
@neverfox As a matter of fact, I was running `1.0.0-beta`.
