### ISSUE TITLE
JSON.stringify missing for body?

### ISSUE THREAD

**Issue by mohanzhang** [agraboso/redux-api-middleware#3]
I am getting the impression I am the first person other than you to use this package :) This is good because now we are in the same boat ;)

I was having some trouble POSTing and PUTing, and I found the cause to be the request body not being stringified. The example on [the fetch readme](https://github.com/github/fetch) (find "Post JSON") shows this:

```js
fetch('/users', {
  method: 'post',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    name: 'Hubot',
    login: 'hubot',
  })
})
```

Perhaps wrap `JSON.stringify(body)` on this line? https://github.com/agraboso/redux-api-middleware/blob/master/src/index.js#L41

**Comment by agraboso** [comment]
You're right! In fact, after reading the [fetch specification](https://fetch.spec.whatwg.org), I think it'd be better to allow `[CALL_API].body` to be of any type, remarking that it should be a valid body according to the fetch specification. You can then `JSON.stringify` the body yourself.
