### ISSUE TITLE
Tests examples in README

### ISSUE THREAD

**Issue by reneklacan** [agraboso/redux-api-middleware#30]
Hi,

it would be awesome if you could add some testing examples to the README. I tried to follow http://rackt.org/redux/docs/recipes/WritingTests.html and use `thunk` and `redux-api-middleware` as middlewares but HTTP request is never invoked and my tests are always passing even though my `expectedActions` is total bullshit.

Thanks!

**Comment by gilbarbara** [comment]
same problem here, I'm still trying..

**Comment by gilbarbara** [comment]
Got it working @reneklacan 

```javascript
import configureMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import { apiMiddleware } from 'redux-api-middleware';
import nock from 'nock';
import * as Actions from '../actions';

const createMockStore = configureMockStore([ thunk, apiMiddleware ]);

describe('Async Actions', () => {
	afterEach(() => {
		nock.cleanAll();
	});

	it('should dispatch "POPULAR_SUCCESS" when fetchPopular has been done', (done) => {
		nock('https://api.example.com')
			.get('/v2/popular')
			.reply(200, { payload: 'OK!' });

		const expectedActions = [
			{ type: 'POPULAR_REQUEST', payload: undefined, meta: undefined },
			{ type: 'POPULAR_SUCCESS', payload: { payload: 'OK!' }, meta: undefined }
		];

		const store = createMockStore({ payload: 'OK!' }, expectedActions, done);
		store.dispatch(fetchPopular());
	});
});
```
Since the mocked store compares with [expect](https://github.com/mjackson/expect) `toEqual` you should pass all the parameters, including payload and meta even when `undefined`

**Comment by jtribble** [comment]
You might also run into an issue with mocking failure action payloads, since the real error object is an ApiError instance that extends Error. Here's an example to test failure actions:

    import {apiMiddleware, ApiError} from 'redux-api-middleware';
    import configureMockStore from 'redux-mock-store';
    import promiseMiddleware from 'redux-promise';
    import thunkMiddleware from 'redux-thunk';
    import * as actions from '../../src/action_creators/auth';
    import initialState from '../../src/store/initial_state';
    import nock from 'nock';

    // configure initial state and mock store
    const initialAuthState = initialState.get('auth');
    const mockStore = configureMockStore([
      thunkMiddleware,
      apiMiddleware,
      promiseMiddleware
    ]);

    // describe unit
    describe('createSession() async action creator', () => {
      afterEach(() => {
        nock.cleanAll();
      });

      it('dispatches FAILURE_CREATE_SESSION action on failed request', done => {
        const apiResponse = {
          message: 'Unexpected token <'
        };

        nock('http://api.example.com')
          .post('/session')
          .reply(500, apiResponse);

        const expectedActions = [
          {
            meta: undefined,
            payload: undefined,
            type: 'REQUEST_CREATE_SESSION'
          },
          {
            error: true,
            meta: undefined,
            payload: new ApiError(500, 'Internal Server Error', apiResponse),
            type: 'FAILURE_CREATE_SESSION'
          }
        ];

        const store = mockStore(initialAuthState, expectedActions, done);

        store.dispatch(actions.createSession({
          user: 'john@example.com',
          password: 'changeme'
        }));
      });
    });

**Comment by anupvarghese** [comment]
Something related to this, 

I need to integrate karma test-runner, however it won't support `nock`.

Is it possible to mock the api call with `sinon`?

I want to achieve something like this,

Instead of,
```
nock('http://api.example.com')
      .post('/session')
      .reply(500, apiResponse);
```
use `sinon`
```
const server = sinon.fakeServer.create();
server.autoRespond = true;
server.respondWith('http://api.example.com/session'),
   [
      500,
      { 'Content-Type': 'application/json' },
      JSON.stringify(apiResponse)
   ]
);
```
But I get error as `reason: Nock: No match for request POST`

**Comment by talexand** [comment]
The examples above and [redux docs](http://redux.js.org/docs/recipes/WritingTests.html) don't seem to match the API anymore. 

`const store = mockStore(initialAuthState, expectedActions, done);` The returned value of `configureMockStore()` doesn't seem to be a function with this signature, at least not from what I can tell from the README and source.

**Comment by kidjp85** [comment]
I'm having the same problem like @reneklacan now.  Nock is not working at all.

**Comment by talexand** [comment]
This worked for us (example strings adapted from working code):

```js
import test from 'ava';
import configureMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import { apiMiddleware } from 'redux-api-middleware';
import nock from 'nock';

import { API } from '../src/asyncActions';

const createMockStore = configureMockStore([thunk, apiMiddleware]);

test.cb('each action is a function returning a valid RSAA', t => {
  test.afterEach.always('nock cleanup', () => nock.cleanAll());

  nock('https://example.com/api')
    .post('/endpoint')
    .reply(200, { payload: 'OK!' });

  const store = createMockStore({});
  store.subscribe(() => {
    const dispatchedActions = store.getActions();

    // assertions for valid action types
    t.true(dispatchedActions
           .map(act => act.type)
           .filter(act => typeof act === 'string')
           .length > 0);
    t.true(dispatchedActions
           .filter(act => act.hasOwnProperty('payload'))
           .length > 0);

    if (dispatchedActions.length === 2) {
      t.end();
    }
  });
  store.dispatch({ [API_CALL]: {
    endpoint: 'https://example.com/api',
    method: 'GET',
    types: ['REQ', 'SUC', 'FAI']
  }});
});
```

**Comment by noahprince22** [comment]
@anupvarghese did you have any luck getting this to work with karma?

**Comment by anupvarghese** [comment]
@noahprince22 Sorry for a late update, I ended up doing something similar as @bright-star suggested.

**Comment by noahprince22** [comment]
@anupvarghese you're still using karma? bright-star's solution uses nock, which doesn't work with karma runner?

**Comment by anupvarghese** [comment]
@noahprince22 👎.. I used it without a runner.

**Comment by chathurilanchana** [comment]
Hi,

I have the below action
export function fetchLoanApplicationStatusList() {
    let url = Config.service_host + Config.lending_api_endpoints.getLoanApplicationStatusList;
    const request = new Request('get', url);
    return request.sendOverMiddleware(null, types.UPDATE_LOAN_APPLICATIONS_STATUS_LIST, types.HANDLE_ERRORS_STATUS_LIST);
}

And then a single class to construct the CALL_API method	sendOverMiddleware(OnCalling, OnCallSuccess, OnCallFailed, body){
		return {
			[CALL_API]: {
				endpoint: this.address,
				method: this.method,
				body: body,
				headers: {
					'Authorization': 'Bearer ' + loadToken(),
					'Accept': 'application/json',
					'Content-Type': 'application/json'
				},
				types: [OnCalling, OnCallSuccess, OnCallFailed]
			}
		};
	}

This works fine with the api. But When I tried to write a unit test as below, response is just {}. Could you please tell me what I'm doing wrong?

  it('should create CALL_API action with GET_ORDER request types', () => {
    const result = filterActions.fetchLoanApplicationStatusList();
    const endpoint = result[CALL_API].endpoint;
    expect(endpoint).toMatch(/allloanapplicationstatus\?.+/);

    expect(result[CALL_API]).to.deep.equal({
      types: [ null, types.UPDATE_LOAN_APPLICATIONS_STATUS_LIST, types.HANDLE_ERRORS_STATUS_LIST ],
      //endpoint: endpoint,
      method: 'GET',
    });
  });

Thank you!

**Comment by AllenFang** [comment]
thanks @bright-star's answer, that's share my example:

```js
import nock from 'nock';
import configureStore from 'redux-mock-store';
import { createStore, applyMiddleware } from 'redux';
import { apiMiddleware, CALL_API } from 'redux-api-middleware';
import { myActionCreator } from 'actions';

const createMockStore = configureStore([ apiMiddleware ]);

describe('redux-api-middleware test', () => {
  describe('myActionCreator', () => {
    const mockPayload = { message: 'success' };

    beforeEach(() => {
      nock('https://example.com/api')
        .get('/endpoint')
        .reply(200, mockPayload);
    });

    it('should dispatch xxx when myActionCreator being called', done => {
      const store = createMockStore({});
      
      store.subscribe(() => {
        const dispatchedActions = store.getActions();
        if (dispatchedActions.length === 1) {
          expect(dispatchedActions[0].type).to.eql(xxx);
          done();
        }
      });
      store.dispatch(myActionCreator());
    });

    it('should dispatch ooo when myActionCreator being called', done => {
      const store = createMockStore({});
      
      store.subscribe(() => {
        const dispatchedActions = store.getActions();
        if (dispatchedActions.length === 2) {
          expect(dispatchedActions[0].type).to.eql(xxx);
          expect(dispatchedActions[1].type).to.eql(ooo);
          expect(dispatchedActions[1].payload).to.eql(mockPayload);
          done();
        }
      });
      store.dispatch(myActionCreator());
    });
  });
});
```

**Comment by renefs** [comment]
I see this issue has been open for a long time. Is there a way to do this properly with jest?

**Comment by nason** [comment]
@renefs as of v2.3.0 you can pass a custom `fetch` implementation into your `RSAA`s https://github.com/agraboso/redux-api-middleware#rsaafetch

You should be able to pass a fetch mock and simulate any kind of scenario in a test now. I'll try to add some docs on testing, but am not sure when I'll be able to. You're more than welcome to open a PR, or to share any notes or examples!

**Comment by renefs** [comment]
Hi @nason, I ended up doing it like this (Version 2.3.0) and seems to work just fine:

```javascript
import configureMockStore from 'redux-mock-store'
import { apiMiddleware } from 'redux-api-middleware'
import thunk from 'redux-thunk'
import fetchMock from 'fetch-mock'

import {getMe} from 'src/actions/user'

const middlewares = [ thunk, apiMiddleware ]
const mockStore = configureMockStore(middlewares)

describe('async me actions', () => {
  afterEach(() => {
    fetchMock.reset()
    fetchMock.restore()
  })

  it('should dispatch ME_SUCCESS when getMe is called', () => {
    const body = {
      email: 'EMAIL',
      username: 'USERNAME'
    }
    fetchMock.getOnce(`https://hostname/api/users/me/`,
      {body: body, headers: {'content-type': 'application/json'}})
    const expectedActions = [
      {type: actions.ME_REQUEST},
      {type: actions.ME_SUCCESS, payload: body}
    ]
    const store = mockStore({})
    return store.dispatch(actions.getMe()).then(() => {
      // return of async actions
      expect(store.getActions()).toEqual(expectedActions)
    })
  })
})
```

The explanation: I'm generating a mock for the request. `getMe()` will return the payload of the mock, which then is checked on the last `expect`.

Cheers.

**Comment by nason** [comment]
Thank you for the notes and the docs PR @renefs! Closing this issue out.
