### ISSUE TITLE
'Unhandled promise rejection' on Firefox

### ISSUE THREAD

**Issue by JoelOtter** [agraboso/redux-api-middleware#35]
Been using this library (v1.0.0-beta3) in Chrome on OS X and it works great, but I'm having issues trying to use it in Firefox. I'm building using the babel-es2015 preset, with Browserify.

On Firefox (43.0.4, latest stable release), I get the following error:

```
Unhandled promise rejection TypeError: action.payload is undefined
```

The success (or failure) action is never dispatched. I'm seeing this happening on Chrome for Android too. Safari works OK.

I'm not sure if this is because I'm not using a required polyfill for Promises or similar - the Babel documentation is a little unclear as to whether the ES2015 preset includes promises.

**Comment by JoelOtter** [comment]
I've tried installing and adding:

```js
require('es6-promise').polyfill();
```

to my app's entry point, but this doesn't appear to make any difference.

**Comment by barrystaes** [comment]
Wow (i have no notable experience with ES6 promises but) that sounds like quite a browser implementation discrepancy. Do you have source for this, and do you know if this behavior changed in the latest/current browser versions?

If the problem persists, should we mention this in the documentation? A PR would be welcome.

**Comment by barrystaes** [comment]
For posterity, JoelOtter said in #45:
> So I'm unable to reproduce #35 now as I'm doing my AJAX 'manually' (Thunk and Axios). I wasn't doing anything particularly strange with the library, though, and it was happening in multiple versions of FF, so hopefully someone can reproduce it.

So this issue is being closed soon after release 1.0.0 unless anyone can confirm the problem still exists in the latest version. (@sylvainlap ?)

**Comment by sylvainlap** [comment]
I never had this promise problem, you can close it ;)

**Comment by nickw** [comment]
@barrystaes I'm experiencing this error with React Native. If I don't provide a custom `payload` function for my `FAILURE` type, then RN throws an `Unhandled promise rejection` error.
