### ISSUE TITLE
3xx status appear as failure? 

### ISSUE THREAD

**Issue by MarkMurphy** [agraboso/redux-api-middleware#39]
After browsing through the repo,  unless I'm mistaken, it appears as though any server response above 299 will be treated as an error. What about redirects ie. (responses with status codes in the 3xx range)?

It think it's a bit awkward to treat a simple redirect as an error, though some clients might want to do that, I can't see all of them wanting to do that.

**Comment by masad-frost** [comment]
+1, main problem is 304

**Comment by barrystaes** [comment]
How could we handle such a redirect.. can `fetch()` handle this?

If this can be improved in a PR, i'd like to merge in the upcoming 2.0 release.

**Comment by nason** [comment]
I believe this comes from the use of [`res.ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) here:

https://github.com/agraboso/redux-api-middleware/blob/cbf0553fac905dc0e7434193d3593dba677d9559/src/middleware.js#L147-L159

If we make this configurable, this middleware should be able to support use cases like this one.

**Comment by nason** [comment]
This is being looked at in https://github.com/agraboso/redux-api-middleware/pull/171

**Comment by nason** [comment]
In 2.x, you can now pass a custom `fetch` implementation
In 3.x (upcoming), you'll be able to pass a custom `ok` check

I think this should be enough to handle most situations, so I'm going to close this out. Feel free to re-open or continue commenting here though.
