### ISSUE TITLE
What to do when response is not JSON?

### ISSUE THREAD

**Issue by mohanzhang** [agraboso/redux-api-middleware#4]
I have a DELETE endpoint that returns 204 No Content as suggested [here](http://jsonapi.org/format/#crud-deleting). Currently, the middleware expects all responses to be JSON, but should this requirement be relaxed?

**Comment by agraboso** [comment]
I think your server should respond with status code 204 and an empty body. The JSON API specification you mention says
> A JSON object MUST be at the root of every JSON API request and response containing data. This object defines a document's "top level".

**Comment by mohanzhang** [comment]
I read that as "a JSON object must be at the root if and only if your request/response contains data" The implication for me is that if the request/response *does not* contain data (e.g. as in 204 No Content), then there may not necessarily be a JSON object, even an empty one (i.e. not even  `{}`). Returning an empty response causes the middleware to blow up when it tries to convert the response to json (I think here: https://github.com/agraboso/redux-api-middleware/blob/master/src/index.js#L51)

**Comment by mohanzhang** [comment]
@agraboso I am not a fan of special-casing a response status in the middleware, but I needed it to move on with my implementation. Just thought I'd show you here in case you have better ideas on how to go about this.

**Comment by agraboso** [comment]
@mohanzhang Check out the `emptyResBody` branch.

My interpretation of the JSON API specification you mentioned in your first post is that

- server responses with data must include the header `Content-Type: application/vnd.api+json`, and
- server responses without data must not include a  `Content-Type` header.

Here are the relevant excerpts:

> ### Content Negotiation
> [...]
> #### Server Responsibilities
> Servers MUST send all JSON API data in response documents with the header `Content-Type: application/vnd.api+json` without any media type parameters.


> ### Document Structure
> [...]
> Unless otherwise noted, objects defined by this specification MUST NOT contain any additional members.

Now, if you look at the code in the `emptyResBody` branch, you'll see that I'm only checking whether the `Content-Type` contains the string `json` before attempting to parse JSON from the response. That is to allow for things like `Content-Type: application/json`. I've also added the test you wrote. The middleware should now correctly emit a `SUCCESS` FSA in response to your 204 with no response data. Let me know if this works for you.

**Comment by mohanzhang** [comment]
Nice! This is a really elegant solution IMO. I tried it just now and it works great! Way better than my hack :) :+1:

**Comment by agraboso** [comment]
Great! I'll push it to npm as 0.4.1 then.
