### ISSUE TITLE
Fork or move to Rackt organisation?

### ISSUE THREAD

**Issue by barrystaes** [agraboso/redux-api-middleware#41]
This project (based on redux real-world example) has stirred quite a few people, but currently the author is not responding or allowing PR's. I hope he does return, if only to ask/allow new maintainers to step up. 

The last commit was 3 months ago, and right now there are 7 PR's and 13 issues. Besides these people contributing, there are 32 forks and 131 stargazers.

I do feel there is quite some momentum here, especially by the users of the library. For other projects where the users maintain the project i've seen ad-hoc organisations like [Rackt](https://github.com/rackt) bring this together and lower the burden on the owner.

On that note, i wonder what the Rackt crew thinks of `redux-api-middleware`. So let me CC them here.. @acdlite, @ellbee, @faassen, @gaearon, @jlongster, @knowbody, @mjackson, @mzabriskie, @omnidan, @prattsj, @pwmckenna, @ryanflorence, @taion, @timdorr.

Do you use `redux-api-middleware`? What is your take on it, and what do you currently use as API middleware?

**Comment by knowbody** [comment]
omg, I was actually thinking about something like that a few months ago :)

I haven't used this project though...

@barrystaes it has MIT license why don't you just fork it yourself and continue working on it? as you started the conversation you are probably a person who knows what's going on and what is missing or needs fixing. I'm sure others will jump in and help.

(*Speaking now for myself*) I don't think it make sense to just put it under the Rackt organisation, it won't solve any problems. The project still needs to have maintainers, otherwise it will be also dead there.

**Comment by agraboso** [comment]
@barrystaes Passing on this project to someone that can keep maintaining it has been on my mind for some time now. I'd love to continue maintaining it myself, but despite my best intentions I can't find the time to do it. So yes, I'd be glad to let somebody step in.

**Comment by taion** [comment]
:+1: I don't see a strong case for moving this under the Rackt org. I think we pulled in redux-simple-router because it was the de facto way to use two Rackt projects together – this looks cool at a glance but I don't see why it'd fall under Rackt per se.

**Comment by timdorr** [comment]
Not a user. This is one of a few different side effects solutions for Redux. I would hesitate to move this to Rackt for two reasons:

1. We don't want to play favorites when the whole redux effect ecosystem is still evolving. There are still plenty of ideas out there and picking one may signal others to stop. Rackt isn't some exclusive club to get in to (I mean, *I* got in it!), but it does send some signals to others, however implicit that may be. 
2. There isn't an active maintainer on the project. Moving it would give more visibility, but doesn't mean we would see more development activity. I'd like to see that first before it gets wrapped up in an org.

It sounds like this needs a fork. If you can get @agraboso's blessing, even better. Have you pursued contacting them directly?

**Comment by timdorr** [comment]
@agraboso How about adding @barrystaes as a committer here as a first step. If he has any other recommendations for maintainers, you can add them too. And if you like the work being done, you can let people npm publish the project and then you're on autopilot :smile:

**Comment by barrystaes** [comment]
@agraboso Thanks for responding here!

I am only barely wrapping my head around `redux-api-middleware` and dont have anything working yet.. so i am not exactly maintainer material. :) But when i use it in a project i won't hesitate to merge the outstanding PR's in a fork, ofcourse.

**Comment by gaearon** [comment]
I don’t think we want this in Rackt because it’s rather opinionated.
(Which is fine for a separate project.)

You definitely should add people who use it as contributors. :-)

**Comment by barrystaes** [comment]
Thanks all. I believe this concludes this issue, i dont want to spam you all more as i already did. :)

I hope to use `redux-api-middleware` in my project and step up as a contributor myself in the near future, starting with documentation, reference implementation, or example use in another FOSS project.

**Comment by barrystaes** [comment]
@agraboso I might ask a lot of questions the next day or two.. :)
And i hope to combine everything i learned in new "getting started?" documentation and an implementation.
