### ISSUE TITLE
Request type option when passing headers

### ISSUE THREAD

**Issue by DriesS** [agraboso/redux-api-middleware#46]
Hello,

When I pass headers to my POST api call, the method is changing to OPTIONS, is there a reason for this?

Here you can find my code 

```javascript
export function addUser(user) {
  return {
    [CALL_API]: {
      endpoint: API_ROOT + '/users/',
      method: 'post',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(user),
      types: [
        types.CREATECOLLECTION_REQUEST,
        {
          type: types.CREATECOLLECTION_SUCCESS,
          payload: (action, state, res) => {
            const contentType = res.headers.get('Content-Type');
            if (contentType && ~contentType.indexOf('json')) {
              // Just making sure res.json() does not raise an error
              return res.json().then((json) => normalize(json, userSchema));
            }
          }
        },
        types.CREATECOLLECTION_FAILURE
      ]
    }
  };
}
```

Result from the api is 

> OPTIONS /api/users/ => generated 0 bytes in 2 msecs (HTTP/1.1 204)

 /api/users/ => generated 0 bytes in 2 msecs (HTTP/1.1 204)

**Comment by barrystaes** [comment]
This is due to CORS, not `redux-api-middleware`.

A recent browser always does an OPTIONS request prior to a HTTP (non-GET?)
request to another domain. If the OPTIONS response does not comply, the
browser wont do the request. So you might want to add CORS support to your
api or move it to the same domain as the app.
Op 19 feb. 2016 12:40 schreef "Dries Steenhouwer" <notifications@github.com

**Comment by ericmash** [comment]
You can quickly test by using the Chrome plugin [Allow-Control-Allow-Origin: *](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog).

I used this plugin to bypass the security check before I added the CORS support to the API recently.
