### ISSUE TITLE
How can I call an API after an API called?

### ISSUE THREAD

**Issue by Darmody** [agraboso/redux-api-middleware#53]
I want to call an API with params which get from the response of another API call.How can I do it?

**Comment by rudin** [comment]
It's being described right here:
https://github.com/agraboso/redux-api-middleware/issues/21

`export function doStuff() {
    return dispatch => {
        dispatch({
            [CALL_API]: {
                ...
                types: [
                    Constants.SOMETHING_FETCHED,
                    {
                        type: Constants.SOMETHING_FETCHED_SUCCEEDED,
                        payload: (action, state, res) => {
                            return res.json().then(json => {
                                dispatch(myAction());
                                return json;
                            });
                        },
                    },
                    Constants.SOMETHING_FETCHED_FAILED,
                ],
                ...`

note: redux-thunk needed

**Comment by Darmody** [comment]
I see. Thanks a lot.
