### ISSUE TITLE
How can I POST a request with header Content-Type:application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by Darmody** [agraboso/redux-api-middleware#54]
I try to add a FormData body, but it can't send request any more.

Need help.

**Comment by gigitux** [comment]
How do you resolve?

I try a post request, but don't work

`export function postHouse() {
  console.log("posthouse")
    return {
        [CALL_API]: {
            endpoint: 'http://localhost:9000/api/house',
            method: 'POST',
            headers: { 'Content-Type': 'x-www-form-urlencoded'},
            body: {
              "title":"test"
            },
          }
        }
      }`

**Comment by MrOggy85** [comment]
@gigitux you should stringify your body value.

What is not working? Do you see in your Redux Developer Tools that an action is fired? And do you see in your Dev Tools/Firebug that a request is made?

**Comment by gigitux** [comment]
@MrOggy85 Thanks :)

**Comment by MrOggy85** [comment]
@gigitux Did the stringification of the body object resolve your problem?

**Comment by gigitux** [comment]
@MrOggy85 Yes
```
export function postHouse(id,title,andress,photo,category,location) {
    return {
        [CALL_API]: {
            endpoint: 'http://localhost:9000/api/house',
            method: 'POST',
            headers: { 'Content-Type': 'application/json'},
            body: JSON.stringify({
                id: id,
                title: title,
                andress: andress,
                photo: photo
            }),
            types: [
                types.POSTHOUSE_SUCCESS,
                {
                    type: types.POSTHOUSE_SUCCESS,
                    payload: (action, state, res) => {
                        return res.json();
                    }
                },
                'FAILURE'
            ]
        }
    }
}
```
