### ISSUE TITLE
How do I get Authorization header into this workflow, possibly in a middleware or more elegant way?

### ISSUE THREAD

**Issue by jordan112** [agraboso/redux-api-middleware#56]
Currently doing it this way, but I know there is a more elegant way.  I pull the id token that i got from authenticating from local storage.

```js

// setup at the top
import * as types from '../constants/ActionTypes'
import { CALL_API } from 'redux-api-middleware';
var ls = require('local-storage')

// my action creator
export function fetchLocations(){
  return {
    [CALL_API]: {
      endpoint: 'http://api.somesite.com/api/locations',
      method: 'GET',
      headers: { 'Content-Type': 'application/json', 'Authentication': ls.get('id_token') || '' },
      types: ['REQUEST', 'SUCCESS', 'FAILURE']
    }
  }
}
'''

**Comment by benpickles** [comment]
I am doing something similar but storing the auth token in the state (fetching it from localStorage when initialising the app) and using a custom middleware to inject the `Authentication` header (so I don't have to manually do it for every action).

**Comment by jordan112** [comment]
"custom middleware to inject the authentication header".  Yes, that's what I'm looking for.  Got any gists you wouldn't mind sharing?  :)

**Comment by benpickles** [comment]
Sure: https://gist.github.com/benpickles/c8f4f45ebdce4bd4d878

**Comment by jordan112** [comment]
Cheers @benpickles   Thanks.

**Comment by jordan112** [comment]
Hey @benpickles , how do you use this gist? I didn't look like middleware.  Do you then add **callApi** to your actions?  Sorry, still learning redux.

**Comment by benpickles** [comment]
Hope this helps, let me know.

https://gist.github.com/benpickles/b465db90ca11adc9ea00
