### ISSUE TITLE
How to send GET parameters?

### ISSUE THREAD

**Issue by andrewQwer** [agraboso/redux-api-middleware#59]
Hi, I'm trying to send some parameters with GET request, but have no idea how to do it. 
Btw, when you initialize body parameter with method GET fetch requests stop working without any errors in console.

```javascript
endpoint: <some_url>
method: 'GET',
body: JSON.stringify({userId: userId}),
```

**Comment by jarrod268** [comment]
Is there a specific reason why you're wanting to use the body of the request and not build out your route/query string instead with your parameters?

**Comment by andrewQwer** [comment]
I don't mean to use body for GET requests, I just think that it would be much easier to specify GET parameters like ` data:{userId:id}` instead of converting JSON to query string like this: `endpoint:<some_url>+'?'+queryString`.

**Comment by agraboso** [comment]
You might want to use node's `querystring`, which is available as a [standalone module](https://www.npmjs.com/package/querystring).

**Comment by iamricky** [comment]
@agraboso I immediately thought of `querystring` as well but I think it would also be beneficial to add this feature to the middleware, then create a `[CALL_API].query` property.

**Comment by aray12** [comment]
In case anyone wants this functionality it is really easy to add with your own middleware (just make sure it is composed before your `redux-api-middleware`.

Here is a snippet I created
https://gist.github.com/aray12/7f859c5eb04201517f9e3be5491023d8

**Comment by s33h0w** [comment]
I think it would be convenient to add `params` as  `[RSAA]`'s property which can used as the `endpoint` parameters.
