### ISSUE TITLE
Accessing action.endpoint from meta and action in RSAA descriptors

### ISSUE THREAD

**Issue by amangeot** [agraboso/redux-api-middleware#66]
Hello,

I am trying to display the `action.endpoint` in `meta` or `payload`, but it ends up showing `undefined` in dev tools. Everything else is working, the actions are normally dispatched and the result from the API is also ok
```
[CALL_API]: {
    endpoint: 'http://example.com/api',
    method: 'GET',
    types: [
      {
        type: 'REQUEST',
        meta: (action, state) => ({ endpoint: action.endpoint })
      },
      {
        type: 'SUCCESS',
        payload: async function (action, state, res) {
          const contentType = res.headers.get('Content-Type')
          // Just making sure res.json() does not raise an error
          if (contentType && ~contentType.indexOf('json')) {
            return await res.json()
          }
        }
      },
      'FAILURE'
    ]
  }
```

Same goes with `payload` instead of `meta` in the RSAA descriptor. Is there something missing ?

Thank you !

**Comment by agraboso** [comment]
The `action` passed to the `meta` and `payload` functions is the original RSAA, so `endpoint` is inside of  the `[CALL_API]` property. You should change `action.endpoint` to `action[CALL_API].endpoint`.

**Comment by amangeot** [comment]
Awesome, it shows the endpoint as expected, thanks for the explaination too !
