### ISSUE TITLE
Middleware to time and log delays between request and reponse (with code)

### ISSUE THREAD

**Issue by amangeot** [agraboso/redux-api-middleware#69]
I wrote a middleware so that we can easily time delays between request and success/failure. I thought I could share if anyone is interested. It does not work if a second similar request is sent before a response to the first one is received. If you know how to deal with this, let me know. 

Here is the output:
> Dispatching A_REQUEST
> Received A_SUCCESS after 500ms

Here is how to activate it for a single request via meta in a RSA action:
`meta: { timer: [A_SUCCESS, A_FAILURE] }` or `meta: { timer: A_SUCCESS }`

And here is the middleware:
```
// Holds a timestamp for each expected action
const timers = {}

const apiTimeLoggerMiddleware = (store) => (next) => (action) => {
  if (action.meta && action.meta.timer) {
    const expected = action.meta.timer
    if (typeof expected === 'string' || expected instanceof String) {
      timers[expected] = new Date().getTime()
      console.log(`Dispatching ${action.type}`)
    } else if (Array.isArray(expected)) {
      const timestamp = new Date().getTime()
      for (const item of expected) { timers[item] = timestamp }
      console.log(`Dispatching ${action.type}`)
    } else {
      console.error(`${action.type} has a \'timer\' meta with unexpected type of ${typeof expected}.`)
    }
  }

  if (action.type in timers) {
    console.log(`Received ${action.type} after ${new Date().getTime() - timers[action.type]}ms`)
  }

  return next(action)
}

export default apiTimeLoggerMiddleware
```

**Comment by patrickgordon** [comment]
FWIW I really am grateful you posted this - it helped me write my own middleware to solve something so thanks for that.

**Comment by froginvasion** [comment]
This could also be a helpful guideline or recipe like #74 was written by @patrickgordon ?
