### ISSUE TITLE
redux-thunk, return promise

### ISSUE THREAD

**Issue by eventhough** [agraboso/redux-api-middleware#7]
Is there a way to use this middleware along with redux-thunk so we can do promise chaining after the fetch completes? For example, some react form libraries require validation errors to be returned after form submission.

**Comment by agraboso** [comment]
@eventhough Can you elaborate on what you would expect `redux-api-middleware` to return? As it stand sright now, I don't think it's possible to chain it with `redux-thunk`, but I'd like to know what it is that you have in mind to see if it is a use case that could be supported or not.

**Comment by eventhough** [comment]
Many popular form libraries like [formsy-react](https://github.com/christianalfoni/formsy-react) or [redux-form](https://github.com/erikras/redux-form) allow the user to set server validation errors after a form has been submitted. Generally speaking we have to return those errors from the form submit handler.

Usually you create some method in your component like:

```javascript
handleSubmit() {
  fetch('http://someapi.com')
  .then((result) => {
    if (result.status === 400) {
      return Promise.resolve(result.validationErrors); // something like this
    }
  });
}
```

The `validationErrors` object is usually a map of form inputs to errors like "length must be at least 10 characters" etc.

redux-thunk allows me to use promise chaining so that after the dispatch is called it updates my store AND returns the actual response so I can display errors back to my form. Is there any way for us to handle this type of situation with redux-api-middleware?

**Comment by agraboso** [comment]
I still think that chaining `redux-api-middleware` with `redux-thunk` is not possible &mdash; at least not in any sense I can think of. But there is something in v0.5.0 that does allow you to access validation errors as in your example above: PR #6 includes the response of an unsuccessful API request.

So say that you dispatch the following RSAA-action,
```js
{
  [CALL_API]: {
    endpoint: 'http://someapi.com',
    method: 'POST',
    types: ['REQUEST', 'SUCCESS', 'FAILURE'],
    body: /* the info from your form */,
    headers: { 'Content-Type': 'application/json' }
  }
}
```
and the server response has a `400` status (as you say above), a `Content-Type: application/json` header and a JSON body. `redux-api-middleware` would dispatch an FSA with

- the `type` property set to `'FAILURE'`, and
- the `payload` property set to an error object (actually an `ApiError` object, with `ApiError` being a class extending the native JS `Error` object) with the following properties:
  - `status: 400`,
  - `statusText: 'Bad Request'`,
  - `message: '400 - Bad Request'`, and
  - `response`: the parsed JSON object of the response (what you called `result` in your post), which would contain the `validationErrors` object you're looking for.

You would then need some custom logic in your reducers and components to parse these validation errors and display the appropriate message to the end user.

If you have an idea of how `redux-api-middleware` could handle this better, I'd love to hear it &mdash; although I'm afraid it just isn't possible without a major change in the way this middleware works, in which case you might be better off using `redux-thunk` directly.

**Comment by neverfox** [comment]
@eventhough The idea of handling a rejected promise in the component, as recommended by redux-form, feels very un-redux to me. The whole point of redux is to get that kind of stuff out of our components and into action creators and reducers. I would suggest handling the FAILURE action on the form reducer itself (using the `plugin` method), setting the values on state that would have been set magically by redux-form.

**Comment by barrystaes** [comment]
For posterity, i believe that https://github.com/agraboso/redux-api-middleware/issues/15 added promise support.
