### ISSUE TITLE
Uncaught TypeError: Cannot read property 'async' of undefined

### ISSUE THREAD

**Issue by zedd45** [agraboso/redux-api-middleware#83]
I'm using `npm v3.8.6` and [`"babel-core": "^6.4.0"`](https://github.com/babel/babel/tree/master/packages/babel-core).  

When I or another dev switch back to `npm v2.x.x`, our app compiles fine.  While using `npm v3.8.6`, however, we get the error named in the subject.  

I don't completely understand this behavior, and it may be a "red herring," because you don't have any `peerDependencies` and that was one of the big breaking changes from 2=>3 in `npm`.  I wonder if it's the folder structure in 3 (flat vs the old "nested" approach)?

My other theory is because we're using babel 6, there is some conflict with the babel 5 / babel runtime.

Here's the (compiled) line in question: 

```
var _regeneratorRuntime = require('babel-runtime/regenerator')['default'];  
```

The above line is presumably from [`babel-runtime v5.x.x`](https://github.com/agraboso/redux-api-middleware/blob/master/package.json#L29).  The [docs for that package](https://github.com/babel/babel/tree/master/packages/babel-runtime) on npm / github aren't very helpful :) 

Back to the actual issue: the line below fails to evaluate (it results in `undefined`): 

```
      return _regeneratorRuntime.async(function callee$2$0$(context$3$0) {
```

This causes my app to halt / crash before even loading my React components, leaving a very broken page.  I'm not really sure how to address this, or even entirely sure I understand the underlying issue.  Any insight would be much appreciated.

**Comment by zedd45** [comment]
File in question: 
./~/redux-api-middleware/lib/middleware.js

**Comment by aalin** [comment]
I got the same. It seems like it has to do with `babel-runtime`.

I solved it in my project by adding the following in the top of my entrypoint.

    const regeneratorRuntime = require('babel-runtime/regenerator');

    if (!regeneratorRuntime.default) {
      regeneratorRuntime.default = regeneratorRuntime;
    }

I guess that redux-api-middleware needs to be built with babel 6 in order to work properly for babel 6 users.

**Comment by zedd45** [comment]
I read somewhere that this has something to do with the `babel-polyfill`.  I don't think this is what tipped me and my teammate off to it, but in [`Redux advanced example`](https://github.com/reactjs/redux/blob/master/docs/advanced/ExampleRedditAPI.md#entry-point) it is the first import.  We haven't restored `redux-api-middleware` to our project quite yet, but IIRC in local testing, this fixed it.

**Comment by mewben** [comment]
I also have this problem :(

Node: v6.3.1
Npm: v3.10.5
OSX

**Comment by cpbotha** [comment]
None of the work-arounds worked for me.

I tracked it down to the official redux-api-middleware expecting an older version of the babel-runtime where the regenerator and other modules were `require()`d with a `['default']`.

Instead of trying to fix that, I consulted the forks on github, and then discovered that aftonbladet's fork works perfectly on my babel6 + webpack2 setup. See https://www.npmjs.com/package/@aftonbladet/redux-api-middleware

You can for example use an alias in your webpack config so that your code doesn't even have to change.

Have fun.

**Comment by ModuloM** [comment]
I had that problem after upgrading dependencies... I couldn't get it working so I had downgraded most of them.
Node 5.12.0
Mac OSX 10.11.6

@cpbotha solution fixed it for now (thanks for sharing)!
Is there any chance that this fork will be merged in the official one?

**Comment by agraboso** [comment]
Version 2 of `redux-api-middleware` will be built against babel 6 instead of babel 5. Work towards it is on the `next` branch (including the aforementioned babel upgrade).

**Comment by abarisic86** [comment]
This error started to appear to me after upgrade of react-scripts to version 1.0.7. After installing @next version of redux api middleware; nothing changed.

I'm injecting headers and maybe something there isn't according to docs but I can't see it.

`import { CALL_API } from 'redux-api-middleware'

const apiAuthInjector = store => next => (action) => {
  const apiAction = action[CALL_API]
  // check if this action is a redux-api-middleware action
  if (!apiAction) {
    return next(action)
  }

  const auth = store.getState().auth

  if (!auth || !auth.token) {
    return next(action)
  }

  apiAction.headers = Object.assign({}, apiAction.headers, {
    Authorization: `Bearer ${auth.token}`,
  })

  return next(action)
}

export default apiAuthInjector
`

**Comment by morgler** [comment]
I'm experiencing the same problem after upgrading react-scripts to 1.0.10. I also use authorization headers like @abarisic86 – maybe that causes the problem?

**Comment by ivchenkodima** [comment]
@morgler Have you find out the solution?

**Comment by morgler** [comment]
@ivchenkodima unfortunately not. I moved to a different gem instead.
