### ISSUE TITLE
what does 'type descriptor' mean?

### ISSUE THREAD

**Issue by mrdulin** [agraboso/redux-api-middleware#84]
I read and found from the doc.

`[CALL_API].types` can be a string, a `Symbol` and a type descriptor.
 
what's the "type descriptor" mean ?

Thanks!

**Comment by agraboso** [comment]
Read the [Customizing the dispatched FSAs](https://github.com/agraboso/redux-api-middleware#customizing-the-dispatched-fsas) section of the documentation.
