### ISSUE TITLE
isRSAA returning false for positive action

### ISSUE THREAD

**Issue by Vivekbhusal** [agraboso/redux-api-middleware#85]
I have been getting `Actions may not have an undefined "type" property.` error and on going through each line of code, i have come to this point. Validation function isRSAA is returning false for right object.

Can anyone please tell me, if i am missing anything or is this a bug. 

![image](https://cloud.githubusercontent.com/assets/1974260/15957435/a287fe10-2f32-11e6-86fd-c8121d18e2b5.png)

**Comment by Vivekbhusal** [comment]
on more debug: I found `hasOwnProperty` is the major cause..

![image](https://cloud.githubusercontent.com/assets/1974260/15958154/36e54ffa-2f37-11e6-80a5-9467fb4e3ed5.png)

**Comment by Gnative** [comment]
I can report the same issue thou I don't really understand what's going on.

**Comment by Vivekbhusal** [comment]
@agraboso : I would really appreciate your input here. Thanks.

**Comment by frankmarineau** [comment]
@Vivekbhusal @Gnative Did you forget to add the middleware to your store as specified in the "Installation" section of the README? I was getting the same error before doing so 😅 .
