### ISSUE TITLE
POST doesn't pass body (formData) though [CALL_API].body is in the action

### ISSUE THREAD

**Issue by bytewiz** [agraboso/redux-api-middleware#86]
When dispatching the POST action the body is not passed in the request..

Any idea why this happens or have I just completely missed out on the idea of how this works?

Help is much appreciated!

![screen shot 2016-06-10 at 13 24 08](https://cloud.githubusercontent.com/assets/16811871/15962936/bb1dd2ca-2f0e-11e6-9645-987ba1e0dcc5.png)
![screen shot 2016-06-10 at 13 23 54](https://cloud.githubusercontent.com/assets/16811871/15962937/bb213fdc-2f0e-11e6-90a3-e69eaaf1f5f6.png)
![screen shot 2016-06-10 at 13 22 14](https://cloud.githubusercontent.com/assets/16811871/15962938/bb22557a-2f0e-11e6-9fa7-1fe5b4f5a1e5.png)

**Comment by zzswang** [comment]
How do you fix it?

I met the same problem.

**Comment by umayr** [comment]
@zzswang Try to `JSON.stringify(...)` the body object.

**Comment by zzswang** [comment]
Thank you, it works.

**Comment by ngocketit** [comment]
Hmm, why doesn't fetch do that automatically? Anyway, thanks @umayr!

**Comment by cizar** [comment]
Here is my opinionated solution...

```javascript
import { CALL_API } from 'redux-api-middleware'

export const apiBodyStringifier = store => next => action => {
  if (action.hasOwnProperty(CALL_API)) {
    const request = action[CALL_API]
    if (typeof request.body === 'object') {
      request.body = JSON.stringify(request.body)
      request.headers = {
        ...request.headers,
        'Content-Type': 'application/json'
      }
    }
  }
  next(action)
}
```

Should be run before apiMiddleware

```javascript
applyMiddleware(
  apiBodyStringifier,
  apiMiddleware
)
```

**Comment by andreykovalenko** [comment]
updated code
```
import { isRSAA, RSAA } from 'redux-api-middleware';

export const apiBodyStringifier = () => next => action => {
    if (isRSAA(action)) {
        const request = action[RSAA];
        if (typeof request.body === 'object') {
            request.body = JSON.stringify(request.body);
            request.headers = {
                ...request.headers,
                'Content-Type': 'application/json'
            };
        }
    }
    return next(action);
};

applyMiddleware(
  apiBodyStringifier,
  apiMiddleware
)
```
