### ISSUE TITLE
Getting custom headers from res in success type descriptor

### ISSUE THREAD

**Issue by thomn** [agraboso/redux-api-middleware#87]
After a successful HEAD request on a resource, I would like to get a 'result-count' custom header from res, but res.headers.get('result-count') returns « null ».

My header is present in the server response :
![response](https://cloud.githubusercontent.com/assets/4236851/16296086/bc63fea4-392a-11e6-894d-4a3a11afc99c.jpg)

res.headers.get('content-type') returns « application/json; charset=UTF-8 », as expected.

Here's my success type descriptor :
```javascript
const pingsCount = {
    type: actions.GET_PINGS_COUNT,
    payload: (action, state, res) => res.headers.get('result-count')
};
```

And here's my reducer :
```javascript
const count = (state = 0, action) => {
    switch (action.type) {
        case actions.GET_PINGS_COUNT:
            return action.payload;
        
        default: return state;
    }
};
```

Am I doing something wrong ?

**Comment by mclin** [comment]
I had the same problem with a cross-origin request and solved it by adding this header to the response:
Access-Control-Expose-Headers: Custom-Header

http://stackoverflow.com/questions/15042439/cant-get-custom-http-header-response-from-ajax-getallresponseheaders

**Comment by thomn** [comment]
Works wonderfully. Thanks a lot !

**Comment by arbadev** [comment]
i am having this issue also, but @mclin asnwer didn't solve my problem. Maybe i am misunderstanding his answer, this is my action

`export const fetchPending = (page) => ({
  [CALL_API]: {
    types: [
      FETCH_PENDING,
      {
        type: FETCH_PENDING_SUCCESS,
        meta: (action, state, res) => {
          const contentType = res.headers.get('Content-Type')
          const link = res.headers.get('Link')
          console.log('Link', link)
          console.log('contentType', contentType)
          return { page }
        },
      },
      FETCH_PENDING_FAILURE,
    ],
    endpoint: `${baseUrl}/professionals?status=pendingForApproval&page=${page}`,
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Custom-Header': 'Link',
      'Access-Control-Expose-Headers': 'Custom-Header',
      'Access-Control-Allow-Methods': 'GET, POST',
    },
  },
})`

**Comment by mclin** [comment]
@arbadev You're adding those to the request header. They need to be in the response header.

Also Custom-Header is a placeholder for the name of your header (Link), so in the server, you need to add these to the response headers:

'Link': 'whatever',
'Access-Control-Expose-Headers': 'Link'
