### ISSUE TITLE
[RFC] createApiAction action creator creator

### ISSUE THREAD

**Issue by migueloller** [agraboso/redux-api-middleware#88]
Inspired by [`redux-actions`](//github.com/acdlite/redux-actions)' `createAction` , I came up with the following function to create RSAA action creators:

``` js
function createApiAction(rsaa, transform = () => {}) {
  return (...args) => ({
    [CALL_API]: {
      ...rsaa,
      ...transform(rsaa, ...args),
    },
  });
}
```

It lets you write action creators like this:

``` js
const fetchUser = createApiAction({
  types: [
    USER_FETCH_ONE_REQUEST,
    USER_FETCH_ONE_SUCCESS,
    USER_FETCH_ONE_FAILURE,
  ],
  method: 'GET',
  endpoint: (id) => `http://localhost:3000/${id}`,
}, (rsaa, id) => ({ endpoint: rsaa.endpoint(id) }));
```

Which you can then call like this:

``` js
dispatch(fetchUser(1));
```

I would love to hear comments from the community on how useful this could be and how it could be improved (e.g., naming, how the transform is applied, or potentially adding a prefix for the endpoint).

If @agraboso agrees, I would love to implement this and make a PR.

**Comment by GGAlanSmithee** [comment]
This seems like a nice addition. Started looking for this shortly after testing this out for a few API calls.

**Comment by migueloller** [comment]
It looks like this project is dead. 😞
