### ISSUE TITLE
Type descriptors aren't working as specified in the README

### ISSUE THREAD

**Issue by migueloller** [agraboso/redux-api-middleware#89]
The README states that a payload can be added to the dispatched action like so:

``` js
payload: (action, state) => ({ endpoint: action.endpoint })
```

 But in reality, the behavior that gives the expected result is the following:

``` js
payload: (action, state) => ({ endpoint: action[CALL_API].endpoint })
```

Should the implementation or the README be updated?

**Comment by mattjstar** [comment]
+1

**Comment by migueloller** [comment]
It looks like this project is dead. 😞
