### ISSUE TITLE
Internal Error 'Already Read'

### ISSUE THREAD

**Issue by mpolichette** [agraboso/redux-api-middleware#92]
Hey guys, I'm really excited to use this library.

I started implementing some logic, but I am trying to use type descriptors to process the response from my api, however when I define a function for both the `payload` and the `meta`  If i try to access the body from both, I get an error on the second attempt to read the JSON response.  

Am I not processing it correctly?

Here is an example:

```
{
  [CALL_API]: {
    method: 'POST',
    endpoint: (state) => endpoint(state, '/create'),
    headers: (state) => headers(state, {}, { auth: true }),
    body: JSON.stringify(data),
    types: [
      types.REQUEST,
      {
        type: types.RECEIVE_CREATE_EVENT,
        payload: (action, state, res) => 
          getJSON(res).then((json) => normalize(json, schema)),
        meta: (action, state, res) => 
          getJSON(res).then((json) => {
            // !!! This never gets called because getJSON(res) causes an 'Already Read' error
            const { id } = json
            return { notify: `Created Id: ${id}` }
          }),
      },
      types.REQUEST_CREATE_EVENT_FAILED,
    ],
  },
}

```

**Comment by mpolichette** [comment]
Current work around for me is to mutate the res object in the payload since it will be called first first. 

I just do this:
```
getJSON(res).then((json) => {
  res.json = json // eslint-disable-line
  return normalize(json, schema)
}),
```

**Comment by mpolichette** [comment]
Seems like the other way to solve this would be for you to pass a clone of the response object:
`res.clone()`
https://developer.mozilla.org/en-US/docs/Web/API/Request/clone

**Comment by developer239** [comment]
Thank you for your time but none of those solutions worked. I tried everything. Getting it using `text()`, `body()`, `blob()`, ...

**Comment by developer239** [comment]
I just fixed problem similar to yours. I found out that you cannot acces payload in meta property. There is just no way. You need to divide your logic between meta and payload property.

       {
        type: types.RECEIVE_CREATE_EVENT,
        payload: (action, state, res) => {
          getJSON(res).then((json) => {
            getJSON(res).then((json) => normalize(json, schema))
            const { id } = json
            handleTheseData({ notify: `Created Id: ${id}` })
          }),
       }  
      }

**Comment by iamandrewluca** [comment]
Create own `getJSON` :)
```js
import { getJSON as noCloneGetJSON } from 'redux-api-middleware'

export function getJSON(res) {
  return noCloneGetJSON(res.clone())
}
```
