### ISSUE TITLE
Typings/declaration files for use with TypeScript

### ISSUE THREAD

**Issue by shzhng** [agraboso/redux-api-middleware#93]

**Comment by teofilusrobert** [comment]
Asking the same question here...
Or is there any similar like redux-api-middleware for typescript?

**Comment by rluiten** [comment]
I am also looking for one of these.

At the moment i created a trivial starting point for what I need to get going, and just have it called redux-api-middleware.d.ts in a typings folder i my project.

```
declare module 'redux-api-middleware' {
  const __temp: {
    CALL_API: any;
    apiMiddleware: any;
  };

  export = __temp;
  // export default _temp; // for other module type
}
```

My primary issue at moment is around trying to extend the definition of Dispatch to directly support actions created for redux-api-middleware as they don't contain a field 'type'.

I have looked at how redux-thunk does it.  https://github.com/gaearon/redux-thunk/blob/master/index.d.ts, but havnt figure that bit out yet. so casting my  action creators to any at moment.

**Comment by mosen** [comment]
I've created a set of definitions for one of my projects at https://github.com/mosen/commandment/blob/master/ui/src/typings/redux-api-middleware.d.ts
if you want to use this as a starting point. I created it for v1 so apologies if it's not fully updated.

**Comment by Keksike** [comment]
@mosen you could wrap that up and send it to definitely-typed to get it into a @types -npm package.

And thanks a lot for sharing that with us! :)

**Comment by mosen** [comment]
@keksike can do. Would also be good to get the .d.ts upstream into the npm package :)

**Comment by jamalsoueidan** [comment]
@mosen Did you just remove your redux-api-middleware typing declaration? :(

**Comment by mosen** [comment]
No don't think so. Oh haha I moved it to a different user. I'll post the link or better yet submit to definitelytyped

**Comment by jamalsoueidan** [comment]
It will be great if you submit for version 2.0, please see my issue maybe you can help me with that @mosen 

thank you very much!

**Comment by edgars-sirokovs** [comment]
@mosen I don't find `redux-api-middleware` on https://microsoft.github.io/TypeSearch/. Could you post the link please?

**Comment by mosen** [comment]
Sorry did not post it yet. I’ll have to see if the middleware changed

**Comment by kellenlask** [comment]
Well, while mosen is sorting out his stuff, I'll add my quick-and-dirty types so others don't have to create them from scratch: https://gist.github.com/kellenlask/a09c898fa835b3d49f0d99c78a53dfc5

I didn't type options, and it's possible these types aren't entirely correct -- my project is just starting, so I haven't testing any of this in depth.

**Comment by mosen** [comment]
Started a fork of DefinitelyTyped https://github.com/mosen/DefinitelyTyped/commit/eb26f9fa17e058ec6fcf051ca4e3cecb3b7325de

**Comment by jenniferlynparsons** [comment]
Very interested in seeing this working. I've added the files to a "custom_typings" folder on my project and tried adding it to the tsconfig.json file, but it doesn't seem to be recognized. 

Does anyone have a status update for how complete this solution is or willing to point me in the right direction? I'm here at the moment:
https://github.com/jenniferlynparsons/cuppa/tree/typescript-conversion/client

**Comment by timini** [comment]
Does this def file work?

**Comment by mosen** [comment]
I'm still using it although I'm having a tough time with the RSAA action being a symbol because Redux upstream defines it as a string only. But yeah, "works for me". I didn't see any major changes for v3

**Comment by iamandrewluca** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36666

**Comment by iamandrewluca** [comment]
@nason I think this can be closed.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-api-middleware
