### ISSUE TITLE
[question] using Redux API Middleware with Redux CRUD

### ISSUE THREAD

**Issue by Industrial** [agraboso/redux-api-middleware#98]
Hi!

I'm trying to integrate `redux-crud` and `redux-api-middleware` (https://github.com/agraboso/redux-api-middleware).

`redux-crud` uses an action format that is not FSA. This means that the actions generated from `redux-crud`, when used in `redux-api-middleware` e.g.` USERS_FETCH_START/SUCCESS/ERROR` are erroring on `record` property not being found, because one with a `payload` is provided.

I have checked out the `[CALL_API].types` but I can only change the payload, not the event itself.

Is it possible to alter/change the events coming out of `redux-api-middleware` completely?

**Comment by agraboso** [comment]
`redux-api-middleware` is built to return FSAs. If you want to change them into something different, you will have to write you own middleware.
